<?php
session_start();
require 'odd_funcs.php';
$gamedate = "Sunday, October 07, 2012";
if(!isset($_SESSION["SESS_MEMBER_ID"]) || (trim($_SESSION["SESS_MEMBER_ID"]) == ""))
{
$colspan_gameday = "7";
$colspan_header = "4";
$betheader_id = "olPercent2_nd";
$betheadergame_id = "betBoxHeaderHeader_nd";
$bets_disabled = "DISABLED";
}
else
{
$colspan_gameday = "8";
$colspan_header = "5";
$betheader_id = "olPercent2";
$betheadergame_id = "betBoxHeaderHeader";
$bets_disabled = "";
}
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan=" . "$colspan_gameday" . "; id='gameDate'>" . "$gamedate" . "</th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rotHeader'>Rot</th>\n";
echo "<th id='teamNameHeader'>Team</th>\n";
echo "<th id='pointSpreadHeader'>Point Spread</th>\n";
echo "<th id='pointSpreadHeader'>PWP</th>\n";
echo "<th id='pointSpreadHeader'>Moneyline</th>\n";
echo "<th id='ouHeaderLeftHeader'></th>\n";
echo "<th id='ouHeaderRightHeader'>Total</th>\n";
echo "<th id=" . "$betheadergame_id" . ">Amount</th>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<br />\n";
if(isset($_COOKIE["ppkDisplayOdds"]))
{
$odds_type = intval($_COOKIE["ppkDisplayOdds"]);
}
else
{
$odds_type = 0;
}
$gamename_1 = "1:00 PM, FedEx Field, Landover";
$gameNum = "1";
$game_desc_id_1 = "40";
$entry1_rot_1 = "103";
$entry1_name_1 = "Atlanta Falcons";
$entry2_rot_1 = "104";
$entry2_name_1 = "Washington Redskins";
$num_entries_1 = "2";
$point_spread1_sp_1 = "-3.0";
$point_spread2_sp_1 = "+3.0";
$total_pool_sp_1 = "5800.0";
$entry1_pool_sp_1 = "2500.0";
$entry1_odds_sp_1p = "1.32";
$entry2_pool_sp_1 = "3300.0";
$entry2_odds_sp_1p = "0.757575757576";
$max_odds_sp_1 = "1.32";
$entry1_odds_sp_1 = convertOdds($entry1_odds_sp_1p, $odds_type, 0);
$entry2_odds_sp_1 = convertOdds($entry2_odds_sp_1p, $odds_type, $max_odds_sp_1);
$point_spread1_ml_1 = "pk";
$point_spread2_ml_1 = "pk";
$total_pool_ml_1 = "2700.0";
$entry1_pool_ml_1 = "1300.0";
$entry1_odds_ml_1p = "1.07692307692";
$entry2_pool_ml_1 = "1400.0";
$entry2_odds_ml_1p = "0.928571428571";
$max_odds_ml_1 = "1.07692307692";
$entry1_odds_ml_1 = convertOdds($entry1_odds_ml_1p, $odds_type, 0);
$entry2_odds_ml_1 = convertOdds($entry2_odds_ml_1p, $odds_type, $max_odds_ml_1);
$point_spread1_pwp_1 = "-3.0";
$point_spread2_pwp_1 = "+3.0";
$total_pool_pwp_1 = "600.0";
$entry1_pool_pwp_1 = "600.0";
$entry1_odds_pwp_1p = "0.0";
$entry2_pool_pwp_1 = "0.0";
$entry2_odds_pwp_1p = "600.0";
$entry3_pool_pwp_1 = "0.0";
$entry3_odds_pwp_1p = "600.0";
$max_odds_pwp_1 = "600.0";
$entry1_odds_pwp_1 = convertOdds($entry1_odds_pwp_1p, $odds_type, $max_odds_pwp_1);
$entry2_odds_pwp_1 = convertOdds($entry2_odds_pwp_1p, $odds_type, 0);
$entry3_odds_pwp_1 = convertOdds($entry3_odds_pwp_1p, $odds_type, $max_odds_pwp_1);
$point_spread1_ou_1 = "+51.0";
$point_spread2_ou_1 = "-51.0";
$point_spread_ou_1 = "51.0";
$total_pool_ou_1 = "700.0";
$entry1_pool_ou_1 = "0.0";
$entry1_odds_ou_1p = "700.0";
$entry2_pool_ou_1 = "700.0";
$entry2_odds_ou_1p = "0.0";
$max_odds_ou_1 = "700.0";
$entry1_odds_ou_1 = convertOdds($entry1_odds_ou_1p, $odds_type, 0);
$entry2_odds_ou_1 = convertOdds($entry2_odds_ou_1p, $odds_type, $max_odds_ou_1);
$compareName_1 = "Bovada";
$point_spread1_sp_1_cmp = "-3.0";
$entry1_odds_sp_1_cmpp = "0.909091";
$entry1_odds_sp_1_cmp = convertOdds($entry1_odds_sp_1_cmpp, $odds_type, 0);
$overlay1_sp_1 = "45.2%";
$point_spread2_sp_1_cmp = "+3.0";
$entry2_odds_sp_1_cmpp = "0.909091";
$entry2_odds_sp_1_cmp = convertOdds($entry2_odds_sp_1_cmpp, $odds_type, 0);
$overlay2_sp_1 = "-16.7%";
$point_spread1_ml_1_cmp = "pk";
$entry1_odds_ml_1_cmpp = "1.3";
$entry1_odds_ml_1_cmp = convertOdds($entry1_odds_ml_1_cmpp, $odds_type, 0);
$overlay1_ml_1 = "-17.2%";
$point_spread2_ml_1_cmp = "pk";
$entry2_odds_ml_1_cmpp = "0.666667";
$entry2_odds_ml_1_cmp = convertOdds($entry2_odds_ml_1_cmpp, $odds_type, 0);
$overlay2_ml_1 = "39.3%";
$point_spread1_pwp_1_cmp = "-3.0";
$entry1_odds_pwp_1_cmpp = "0.909091";
$entry1_odds_pwp_1_cmp = convertOdds($entry1_odds_pwp_1_cmpp, $odds_type, 0);
$overlay1_pwp_1 = "-100.0%";
$point_spread2_pwp_1_cmp = "+3.0";
$entry2_odds_pwp_1_cmpp = "0.909091";
$entry2_odds_pwp_1_cmp = convertOdds($entry2_odds_pwp_1_cmpp, $odds_type, 0);
$overlay2_pwp_1 = "65899%";
$point_spread3_pwp_1_cmp = "pk";
$entry3_odds_pwp_1_cmpp = "0.0";
$entry3_odds_pwp_1_cmp = convertOdds($entry3_odds_pwp_1_cmpp, $odds_type, 0);
$overlay3_pwp_1 = "0.0%";
$point_spread1_ou_1_cmp = "+52.0";
$entry1_odds_ou_1_cmpp = "0.909091";
$entry1_odds_ou_1_cmp = convertOdds($entry1_odds_ou_1_cmpp, $odds_type, 0);
$overlay1_ou_1 = "76899%";
$point_spread2_ou_1_cmp = "+52.0";
$entry2_odds_ou_1_cmpp = "0.909091";
$entry2_odds_ou_1_cmp = convertOdds($entry2_odds_ou_1_cmpp, $odds_type, 0);
$overlay2_ou_1 = "-100.0%";
echo "<div id='pool_view'>\n";
echo "<form action='bet-exec1.php' method='post' class='f-wrap-100'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_1" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_1" . "<input type='hidden' name='game_desc_id' id='game_desc_id' value=" . "$game_desc_id_1" . "/><input type='hidden' name='rot_id_e1_game1' id='rot_id_e1_game1' value=" . "$entry1_rot_1" . "/><input type='hidden' name='rot_id_e2_game1' id='rot_id_e2_game1' value=" . "$entry2_rot_1" . "/></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_1" . " " . "$entry1_odds_sp_1" . "</label><input type='checkbox' name='spread_game1[]' id='testchecks' value='100odds' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_1" . " " . "$entry1_odds_pwp_1" . "</label><input type='checkbox' name='pwp_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_1" . "</label><input type='checkbox' name='ml_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_1" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_1" . "</label><input type='checkbox' name='overunder_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_1" . "</label><input type='checkbox' name='overunder_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game1' id='betbox_e1_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_1" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_1" . " " . "$entry2_odds_sp_1" . "</label><input type='checkbox' name='spread_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_1" . " " . "$entry2_odds_pwp_1" . "</label><input type='checkbox' name='pwp_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_1" . "</label><input type='checkbox' name='ml_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game1' id='betbox_e2_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_1" . "</label><input type='checkbox' name='pwp_game1[]' value='e3' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game1' id='betbox_e3_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_1" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_1" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_1_cmp" . " " . "$entry1_odds_sp_1_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_1_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_1_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_1" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_1_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_1_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_1" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_1" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_1_cmp" . " " . "$entry2_odds_sp_1_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_1_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_1_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_1" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_1" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</form>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_2 = "1:00 PM, Heinz Field, Pittsburgh";
$gameNum = "2";
$game_desc_id_2 = "39";
$entry1_rot_2 = "101";
$entry1_name_2 = "Philadelphia Eagles";
$entry2_rot_2 = "102";
$entry2_name_2 = "Pittsburgh Steelers";
$num_entries_2 = "2";
$point_spread1_sp_2 = "+3.5";
$point_spread2_sp_2 = "-3.5";
$total_pool_sp_2 = "3700.0";
$entry1_pool_sp_2 = "3300.0";
$entry1_odds_sp_2p = "0.121212121212";
$entry2_pool_sp_2 = "400.0";
$entry2_odds_sp_2p = "8.25";
$max_odds_sp_2 = "8.25";
$entry1_odds_sp_2 = convertOdds($entry1_odds_sp_2p, $odds_type, $max_odds_sp_2);
$entry2_odds_sp_2 = convertOdds($entry2_odds_sp_2p, $odds_type, 0);
$point_spread1_ml_2 = "pk";
$point_spread2_ml_2 = "pk";
$total_pool_ml_2 = "1400.0";
$entry1_pool_ml_2 = "600.0";
$entry1_odds_ml_2p = "1.33333333333";
$entry2_pool_ml_2 = "800.0";
$entry2_odds_ml_2p = "0.75";
$max_odds_ml_2 = "1.33333333333";
$entry1_odds_ml_2 = convertOdds($entry1_odds_ml_2p, $odds_type, 0);
$entry2_odds_ml_2 = convertOdds($entry2_odds_ml_2p, $odds_type, $max_odds_ml_2);
$point_spread1_pwp_2 = "+3.0";
$point_spread2_pwp_2 = "-3.0";
$total_pool_pwp_2 = "1900.0";
$entry1_pool_pwp_2 = "1000.0";
$entry1_odds_pwp_2p = "0.9";
$entry2_pool_pwp_2 = "0.0";
$entry2_odds_pwp_2p = "1900.0";
$entry3_pool_pwp_2 = "900.0";
$entry3_odds_pwp_2p = "1.11111111111";
$max_odds_pwp_2 = "1900.0";
$entry1_odds_pwp_2 = convertOdds($entry1_odds_pwp_2p, $odds_type, $max_odds_pwp_2);
$entry2_odds_pwp_2 = convertOdds($entry2_odds_pwp_2p, $odds_type, 0);
$entry3_odds_pwp_2 = convertOdds($entry3_odds_pwp_2p, $odds_type, $max_odds_pwp_2);
$point_spread1_ou_2 = "+43.5";
$point_spread2_ou_2 = "-43.5";
$point_spread_ou_2 = "43.5";
$total_pool_ou_2 = "1700.0";
$entry1_pool_ou_2 = "1000.0";
$entry1_odds_ou_2p = "0.7";
$entry2_pool_ou_2 = "700.0";
$entry2_odds_ou_2p = "1.42857142857";
$max_odds_ou_2 = "1.42857142857";
$entry1_odds_ou_2 = convertOdds($entry1_odds_ou_2p, $odds_type, $max_odds_ou_2);
$entry2_odds_ou_2 = convertOdds($entry2_odds_ou_2p, $odds_type, 0);
$compareName_2 = "Bovada";
$point_spread1_sp_2_cmp = "pk";
$entry1_odds_sp_2_cmpp = "None";
$entry1_odds_sp_2_cmp = convertOdds($entry1_odds_sp_2_cmpp, $odds_type, 0);
$overlay1_sp_2 = "0.0%";
$point_spread2_sp_2_cmp = "pk";
$entry2_odds_sp_2_cmpp = "None";
$entry2_odds_sp_2_cmp = convertOdds($entry2_odds_sp_2_cmpp, $odds_type, 0);
$overlay2_sp_2 = "0.0%";
$point_spread1_ml_2_cmp = "pk";
$entry1_odds_ml_2_cmpp = "None";
$entry1_odds_ml_2_cmp = convertOdds($entry1_odds_ml_2_cmpp, $odds_type, 0);
$overlay1_ml_2 = "0.0%";
$point_spread2_ml_2_cmp = "pk";
$entry2_odds_ml_2_cmpp = "None";
$entry2_odds_ml_2_cmp = convertOdds($entry2_odds_ml_2_cmpp, $odds_type, 0);
$overlay2_ml_2 = "0.0%";
$point_spread1_pwp_2_cmp = "pk";
$entry1_odds_pwp_2_cmpp = "None";
$entry1_odds_pwp_2_cmp = convertOdds($entry1_odds_pwp_2_cmpp, $odds_type, 0);
$overlay1_pwp_2 = "0.0%";
$point_spread2_pwp_2_cmp = "pk";
$entry2_odds_pwp_2_cmpp = "None";
$entry2_odds_pwp_2_cmp = convertOdds($entry2_odds_pwp_2_cmpp, $odds_type, 0);
$overlay2_pwp_2 = "0.0%";
$point_spread3_pwp_2_cmp = "pk";
$entry3_odds_pwp_2_cmpp = "0.0";
$entry3_odds_pwp_2_cmp = convertOdds($entry3_odds_pwp_2_cmpp, $odds_type, 0);
$overlay3_pwp_2 = "0.0%";
$point_spread1_ou_2_cmp = "pk";
$entry1_odds_ou_2_cmpp = "None";
$entry1_odds_ou_2_cmp = convertOdds($entry1_odds_ou_2_cmpp, $odds_type, 0);
$overlay1_ou_2 = "0.0%";
$point_spread2_ou_2_cmp = "pk";
$entry2_odds_ou_2_cmpp = "None";
$entry2_odds_ou_2_cmp = convertOdds($entry2_odds_ou_2_cmpp, $odds_type, 0);
$overlay2_ou_2 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<form action='bet-exec1.php' method='post' class='f-wrap-100'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_2" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_2" . "<input type='hidden' name='game_desc_id' id='game_desc_id' value=" . "$game_desc_id_2" . "/><input type='hidden' name='rot_id_e1_game1' id='rot_id_e1_game1' value=" . "$entry1_rot_2" . "/><input type='hidden' name='rot_id_e2_game1' id='rot_id_e2_game1' value=" . "$entry2_rot_2" . "/></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_2" . " " . "$entry1_odds_sp_2" . "</label><input type='checkbox' name='spread_game1[]' id='testchecks' value='100odds' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_2" . " " . "$entry1_odds_pwp_2" . "</label><input type='checkbox' name='pwp_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_2" . "</label><input type='checkbox' name='ml_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_2" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_2" . "</label><input type='checkbox' name='overunder_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_2" . "</label><input type='checkbox' name='overunder_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game1' id='betbox_e1_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_2" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_2" . " " . "$entry2_odds_sp_2" . "</label><input type='checkbox' name='spread_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_2" . " " . "$entry2_odds_pwp_2" . "</label><input type='checkbox' name='pwp_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_2" . "</label><input type='checkbox' name='ml_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game1' id='betbox_e2_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_2" . "</label><input type='checkbox' name='pwp_game1[]' value='e3' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game1' id='betbox_e3_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_2" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_2" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_2_cmp" . " " . "$entry1_odds_sp_2_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_2_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_2_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_2" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_2_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_2_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_2" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_2" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_2_cmp" . " " . "$entry2_odds_sp_2_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_2_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_2_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_2" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_2" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</form>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_3 = "1:00 PM, Lucas Oil Stadium, Indianapolis";
$gameNum = "3";
$game_desc_id_3 = "41";
$entry1_rot_3 = "105";
$entry1_name_3 = "Green Bay Packers";
$entry2_rot_3 = "106";
$entry2_name_3 = "Indianapolis Colts";
$num_entries_3 = "2";
$point_spread1_sp_3 = "-7.0";
$point_spread2_sp_3 = "+7.0";
$total_pool_sp_3 = "5000.0";
$entry1_pool_sp_3 = "1700.0";
$entry1_odds_sp_3p = "1.94117647059";
$entry2_pool_sp_3 = "3300.0";
$entry2_odds_sp_3p = "0.515151515152";
$max_odds_sp_3 = "1.94117647059";
$entry1_odds_sp_3 = convertOdds($entry1_odds_sp_3p, $odds_type, 0);
$entry2_odds_sp_3 = convertOdds($entry2_odds_sp_3p, $odds_type, $max_odds_sp_3);
$point_spread1_ml_3 = "pk";
$point_spread2_ml_3 = "pk";
$total_pool_ml_3 = "1100.0";
$entry1_pool_ml_3 = "600.0";
$entry1_odds_ml_3p = "0.833333333333";
$entry2_pool_ml_3 = "500.0";
$entry2_odds_ml_3p = "1.2";
$max_odds_ml_3 = "1.2";
$entry1_odds_ml_3 = convertOdds($entry1_odds_ml_3p, $odds_type, $max_odds_ml_3);
$entry2_odds_ml_3 = convertOdds($entry2_odds_ml_3p, $odds_type, 0);
$point_spread1_pwp_3 = "-7.0";
$point_spread2_pwp_3 = "+7.0";
$total_pool_pwp_3 = "700.0";
$entry1_pool_pwp_3 = "0.0";
$entry1_odds_pwp_3p = "700.0";
$entry2_pool_pwp_3 = "700.0";
$entry2_odds_pwp_3p = "0.0";
$entry3_pool_pwp_3 = "0.0";
$entry3_odds_pwp_3p = "700.0";
$max_odds_pwp_3 = "700.0";
$entry1_odds_pwp_3 = convertOdds($entry1_odds_pwp_3p, $odds_type, 0);
$entry2_odds_pwp_3 = convertOdds($entry2_odds_pwp_3p, $odds_type, $max_odds_pwp_3);
$entry3_odds_pwp_3 = convertOdds($entry3_odds_pwp_3p, $odds_type, $max_odds_pwp_3);
$point_spread1_ou_3 = "+47.5";
$point_spread2_ou_3 = "-47.5";
$point_spread_ou_3 = "47.5";
$total_pool_ou_3 = "0.0";
$entry1_pool_ou_3 = "0.0";
$entry1_odds_ou_3p = "20";
$entry2_pool_ou_3 = "0.0";
$entry2_odds_ou_3p = "20";
$max_odds_ou_3 = "20";
$entry1_odds_ou_3 = convertOdds($entry1_odds_ou_3p, $odds_type, 0);
$entry2_odds_ou_3 = convertOdds($entry2_odds_ou_3p, $odds_type, $max_odds_ou_3);
$compareName_3 = "Bovada";
$point_spread1_sp_3_cmp = "pk";
$entry1_odds_sp_3_cmpp = "None";
$entry1_odds_sp_3_cmp = convertOdds($entry1_odds_sp_3_cmpp, $odds_type, 0);
$overlay1_sp_3 = "0.0%";
$point_spread2_sp_3_cmp = "pk";
$entry2_odds_sp_3_cmpp = "None";
$entry2_odds_sp_3_cmp = convertOdds($entry2_odds_sp_3_cmpp, $odds_type, 0);
$overlay2_sp_3 = "0.0%";
$point_spread1_ml_3_cmp = "pk";
$entry1_odds_ml_3_cmpp = "None";
$entry1_odds_ml_3_cmp = convertOdds($entry1_odds_ml_3_cmpp, $odds_type, 0);
$overlay1_ml_3 = "0.0%";
$point_spread2_ml_3_cmp = "pk";
$entry2_odds_ml_3_cmpp = "None";
$entry2_odds_ml_3_cmp = convertOdds($entry2_odds_ml_3_cmpp, $odds_type, 0);
$overlay2_ml_3 = "0.0%";
$point_spread1_pwp_3_cmp = "pk";
$entry1_odds_pwp_3_cmpp = "None";
$entry1_odds_pwp_3_cmp = convertOdds($entry1_odds_pwp_3_cmpp, $odds_type, 0);
$overlay1_pwp_3 = "0.0%";
$point_spread2_pwp_3_cmp = "pk";
$entry2_odds_pwp_3_cmpp = "None";
$entry2_odds_pwp_3_cmp = convertOdds($entry2_odds_pwp_3_cmpp, $odds_type, 0);
$overlay2_pwp_3 = "0.0%";
$point_spread3_pwp_3_cmp = "pk";
$entry3_odds_pwp_3_cmpp = "0.0";
$entry3_odds_pwp_3_cmp = convertOdds($entry3_odds_pwp_3_cmpp, $odds_type, 0);
$overlay3_pwp_3 = "0.0%";
$point_spread1_ou_3_cmp = "pk";
$entry1_odds_ou_3_cmpp = "None";
$entry1_odds_ou_3_cmp = convertOdds($entry1_odds_ou_3_cmpp, $odds_type, 0);
$overlay1_ou_3 = "0.0%";
$point_spread2_ou_3_cmp = "pk";
$entry2_odds_ou_3_cmpp = "None";
$entry2_odds_ou_3_cmp = convertOdds($entry2_odds_ou_3_cmpp, $odds_type, 0);
$overlay2_ou_3 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<form action='bet-exec1.php' method='post' class='f-wrap-100'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_3" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_3" . "<input type='hidden' name='game_desc_id' id='game_desc_id' value=" . "$game_desc_id_3" . "/><input type='hidden' name='rot_id_e1_game1' id='rot_id_e1_game1' value=" . "$entry1_rot_3" . "/><input type='hidden' name='rot_id_e2_game1' id='rot_id_e2_game1' value=" . "$entry2_rot_3" . "/></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_3" . " " . "$entry1_odds_sp_3" . "</label><input type='checkbox' name='spread_game1[]' id='testchecks' value='100odds' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_3" . " " . "$entry1_odds_pwp_3" . "</label><input type='checkbox' name='pwp_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_3" . "</label><input type='checkbox' name='ml_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_3" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_3" . "</label><input type='checkbox' name='overunder_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_3" . "</label><input type='checkbox' name='overunder_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game1' id='betbox_e1_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_3" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_3" . " " . "$entry2_odds_sp_3" . "</label><input type='checkbox' name='spread_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_3" . " " . "$entry2_odds_pwp_3" . "</label><input type='checkbox' name='pwp_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_3" . "</label><input type='checkbox' name='ml_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game1' id='betbox_e2_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_3" . "</label><input type='checkbox' name='pwp_game1[]' value='e3' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game1' id='betbox_e3_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_3" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_3" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_3_cmp" . " " . "$entry1_odds_sp_3_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_3_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_3_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_3" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_3_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_3_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_3" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_3" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_3_cmp" . " " . "$entry2_odds_sp_3_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_3_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_3_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_3" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_3" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</form>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_4 = "1:00 PM, MetLife Stadium, East Rutherford";
$gameNum = "4";
$game_desc_id_4 = "42";
$entry1_rot_4 = "107";
$entry1_name_4 = "Cleveland Browns";
$entry2_rot_4 = "108";
$entry2_name_4 = "New York Giants";
$num_entries_4 = "2";
$point_spread1_sp_4 = "+9.0";
$point_spread2_sp_4 = "-9.0";
$total_pool_sp_4 = "2900.0";
$entry1_pool_sp_4 = "1300.0";
$entry1_odds_sp_4p = "1.23076923077";
$entry2_pool_sp_4 = "1600.0";
$entry2_odds_sp_4p = "0.8125";
$max_odds_sp_4 = "1.23076923077";
$entry1_odds_sp_4 = convertOdds($entry1_odds_sp_4p, $odds_type, 0);
$entry2_odds_sp_4 = convertOdds($entry2_odds_sp_4p, $odds_type, $max_odds_sp_4);
$point_spread1_ml_4 = "pk";
$point_spread2_ml_4 = "pk";
$total_pool_ml_4 = "0.0";
$entry1_pool_ml_4 = "0.0";
$entry1_odds_ml_4p = "20";
$entry2_pool_ml_4 = "0.0";
$entry2_odds_ml_4p = "20";
$max_odds_ml_4 = "20";
$entry1_odds_ml_4 = convertOdds($entry1_odds_ml_4p, $odds_type, 0);
$entry2_odds_ml_4 = convertOdds($entry2_odds_ml_4p, $odds_type, $max_odds_ml_4);
$point_spread1_pwp_4 = "+9.0";
$point_spread2_pwp_4 = "-9.0";
$total_pool_pwp_4 = "900.0";
$entry1_pool_pwp_4 = "0.0";
$entry1_odds_pwp_4p = "900.0";
$entry2_pool_pwp_4 = "900.0";
$entry2_odds_pwp_4p = "0.0";
$entry3_pool_pwp_4 = "0.0";
$entry3_odds_pwp_4p = "900.0";
$max_odds_pwp_4 = "900.0";
$entry1_odds_pwp_4 = convertOdds($entry1_odds_pwp_4p, $odds_type, 0);
$entry2_odds_pwp_4 = convertOdds($entry2_odds_pwp_4p, $odds_type, $max_odds_pwp_4);
$entry3_odds_pwp_4 = convertOdds($entry3_odds_pwp_4p, $odds_type, $max_odds_pwp_4);
$point_spread1_ou_4 = "+44.0";
$point_spread2_ou_4 = "-44.0";
$point_spread_ou_4 = "44.0";
$total_pool_ou_4 = "2300.0";
$entry1_pool_ou_4 = "1000.0";
$entry1_odds_ou_4p = "1.3";
$entry2_pool_ou_4 = "1300.0";
$entry2_odds_ou_4p = "0.769230769231";
$max_odds_ou_4 = "1.3";
$entry1_odds_ou_4 = convertOdds($entry1_odds_ou_4p, $odds_type, 0);
$entry2_odds_ou_4 = convertOdds($entry2_odds_ou_4p, $odds_type, $max_odds_ou_4);
$compareName_4 = "Bovada";
$point_spread1_sp_4_cmp = "pk";
$entry1_odds_sp_4_cmpp = "None";
$entry1_odds_sp_4_cmp = convertOdds($entry1_odds_sp_4_cmpp, $odds_type, 0);
$overlay1_sp_4 = "0.0%";
$point_spread2_sp_4_cmp = "pk";
$entry2_odds_sp_4_cmpp = "None";
$entry2_odds_sp_4_cmp = convertOdds($entry2_odds_sp_4_cmpp, $odds_type, 0);
$overlay2_sp_4 = "0.0%";
$point_spread1_ml_4_cmp = "pk";
$entry1_odds_ml_4_cmpp = "None";
$entry1_odds_ml_4_cmp = convertOdds($entry1_odds_ml_4_cmpp, $odds_type, 0);
$overlay1_ml_4 = "0.0%";
$point_spread2_ml_4_cmp = "pk";
$entry2_odds_ml_4_cmpp = "None";
$entry2_odds_ml_4_cmp = convertOdds($entry2_odds_ml_4_cmpp, $odds_type, 0);
$overlay2_ml_4 = "0.0%";
$point_spread1_pwp_4_cmp = "pk";
$entry1_odds_pwp_4_cmpp = "None";
$entry1_odds_pwp_4_cmp = convertOdds($entry1_odds_pwp_4_cmpp, $odds_type, 0);
$overlay1_pwp_4 = "0.0%";
$point_spread2_pwp_4_cmp = "pk";
$entry2_odds_pwp_4_cmpp = "None";
$entry2_odds_pwp_4_cmp = convertOdds($entry2_odds_pwp_4_cmpp, $odds_type, 0);
$overlay2_pwp_4 = "0.0%";
$point_spread3_pwp_4_cmp = "pk";
$entry3_odds_pwp_4_cmpp = "0.0";
$entry3_odds_pwp_4_cmp = convertOdds($entry3_odds_pwp_4_cmpp, $odds_type, 0);
$overlay3_pwp_4 = "0.0%";
$point_spread1_ou_4_cmp = "pk";
$entry1_odds_ou_4_cmpp = "None";
$entry1_odds_ou_4_cmp = convertOdds($entry1_odds_ou_4_cmpp, $odds_type, 0);
$overlay1_ou_4 = "0.0%";
$point_spread2_ou_4_cmp = "pk";
$entry2_odds_ou_4_cmpp = "None";
$entry2_odds_ou_4_cmp = convertOdds($entry2_odds_ou_4_cmpp, $odds_type, 0);
$overlay2_ou_4 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<form action='bet-exec1.php' method='post' class='f-wrap-100'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_4" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_4" . "<input type='hidden' name='game_desc_id' id='game_desc_id' value=" . "$game_desc_id_4" . "/><input type='hidden' name='rot_id_e1_game1' id='rot_id_e1_game1' value=" . "$entry1_rot_4" . "/><input type='hidden' name='rot_id_e2_game1' id='rot_id_e2_game1' value=" . "$entry2_rot_4" . "/></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_4" . " " . "$entry1_odds_sp_4" . "</label><input type='checkbox' name='spread_game1[]' id='testchecks' value='100odds' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_4" . " " . "$entry1_odds_pwp_4" . "</label><input type='checkbox' name='pwp_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_4" . "</label><input type='checkbox' name='ml_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_4" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_4" . "</label><input type='checkbox' name='overunder_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_4" . "</label><input type='checkbox' name='overunder_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game1' id='betbox_e1_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_4" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_4" . " " . "$entry2_odds_sp_4" . "</label><input type='checkbox' name='spread_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_4" . " " . "$entry2_odds_pwp_4" . "</label><input type='checkbox' name='pwp_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_4" . "</label><input type='checkbox' name='ml_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game1' id='betbox_e2_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_4" . "</label><input type='checkbox' name='pwp_game1[]' value='e3' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game1' id='betbox_e3_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_4" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_4" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_4_cmp" . " " . "$entry1_odds_sp_4_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_4_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_4_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_4" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_4_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_4_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_4" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_4" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_4_cmp" . " " . "$entry2_odds_sp_4_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_4_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_4_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_4" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_4" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</form>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_5 = "1:00 PM, Hubert H. Humphrey Metrodome, Minneapolis";
$gameNum = "5";
$game_desc_id_5 = "43";
$entry1_rot_5 = "109";
$entry1_name_5 = "Tennessee Titans";
$entry2_rot_5 = "110";
$entry2_name_5 = "Minnesota Vikings";
$num_entries_5 = "2";
$point_spread1_sp_5 = "+5.5";
$point_spread2_sp_5 = "-5.5";
$total_pool_sp_5 = "600.0";
$entry1_pool_sp_5 = "600.0";
$entry1_odds_sp_5p = "0.0";
$entry2_pool_sp_5 = "0.0";
$entry2_odds_sp_5p = "600.0";
$max_odds_sp_5 = "600.0";
$entry1_odds_sp_5 = convertOdds($entry1_odds_sp_5p, $odds_type, $max_odds_sp_5);
$entry2_odds_sp_5 = convertOdds($entry2_odds_sp_5p, $odds_type, 0);
$point_spread1_ml_5 = "pk";
$point_spread2_ml_5 = "pk";
$total_pool_ml_5 = "2700.0";
$entry1_pool_ml_5 = "1700.0";
$entry1_odds_ml_5p = "0.588235294118";
$entry2_pool_ml_5 = "1000.0";
$entry2_odds_ml_5p = "1.7";
$max_odds_ml_5 = "1.7";
$entry1_odds_ml_5 = convertOdds($entry1_odds_ml_5p, $odds_type, $max_odds_ml_5);
$entry2_odds_ml_5 = convertOdds($entry2_odds_ml_5p, $odds_type, 0);
$point_spread1_pwp_5 = "+6.0";
$point_spread2_pwp_5 = "-6.0";
$total_pool_pwp_5 = "1000.0";
$entry1_pool_pwp_5 = "0.0";
$entry1_odds_pwp_5p = "1000.0";
$entry2_pool_pwp_5 = "0.0";
$entry2_odds_pwp_5p = "1000.0";
$entry3_pool_pwp_5 = "1000.0";
$entry3_odds_pwp_5p = "0.0";
$max_odds_pwp_5 = "1000.0";
$entry1_odds_pwp_5 = convertOdds($entry1_odds_pwp_5p, $odds_type, 0);
$entry2_odds_pwp_5 = convertOdds($entry2_odds_pwp_5p, $odds_type, $max_odds_pwp_5);
$entry3_odds_pwp_5 = convertOdds($entry3_odds_pwp_5p, $odds_type, $max_odds_pwp_5);
$point_spread1_ou_5 = "+43.5";
$point_spread2_ou_5 = "-43.5";
$point_spread_ou_5 = "43.5";
$total_pool_ou_5 = "2400.0";
$entry1_pool_ou_5 = "1300.0";
$entry1_odds_ou_5p = "0.846153846154";
$entry2_pool_ou_5 = "1100.0";
$entry2_odds_ou_5p = "1.18181818182";
$max_odds_ou_5 = "1.18181818182";
$entry1_odds_ou_5 = convertOdds($entry1_odds_ou_5p, $odds_type, $max_odds_ou_5);
$entry2_odds_ou_5 = convertOdds($entry2_odds_ou_5p, $odds_type, 0);
$compareName_5 = "Bovada";
$point_spread1_sp_5_cmp = "pk";
$entry1_odds_sp_5_cmpp = "None";
$entry1_odds_sp_5_cmp = convertOdds($entry1_odds_sp_5_cmpp, $odds_type, 0);
$overlay1_sp_5 = "0.0%";
$point_spread2_sp_5_cmp = "pk";
$entry2_odds_sp_5_cmpp = "None";
$entry2_odds_sp_5_cmp = convertOdds($entry2_odds_sp_5_cmpp, $odds_type, 0);
$overlay2_sp_5 = "0.0%";
$point_spread1_ml_5_cmp = "pk";
$entry1_odds_ml_5_cmpp = "None";
$entry1_odds_ml_5_cmp = convertOdds($entry1_odds_ml_5_cmpp, $odds_type, 0);
$overlay1_ml_5 = "0.0%";
$point_spread2_ml_5_cmp = "pk";
$entry2_odds_ml_5_cmpp = "None";
$entry2_odds_ml_5_cmp = convertOdds($entry2_odds_ml_5_cmpp, $odds_type, 0);
$overlay2_ml_5 = "0.0%";
$point_spread1_pwp_5_cmp = "pk";
$entry1_odds_pwp_5_cmpp = "None";
$entry1_odds_pwp_5_cmp = convertOdds($entry1_odds_pwp_5_cmpp, $odds_type, 0);
$overlay1_pwp_5 = "0.0%";
$point_spread2_pwp_5_cmp = "pk";
$entry2_odds_pwp_5_cmpp = "None";
$entry2_odds_pwp_5_cmp = convertOdds($entry2_odds_pwp_5_cmpp, $odds_type, 0);
$overlay2_pwp_5 = "0.0%";
$point_spread3_pwp_5_cmp = "pk";
$entry3_odds_pwp_5_cmpp = "0.0";
$entry3_odds_pwp_5_cmp = convertOdds($entry3_odds_pwp_5_cmpp, $odds_type, 0);
$overlay3_pwp_5 = "0.0%";
$point_spread1_ou_5_cmp = "pk";
$entry1_odds_ou_5_cmpp = "None";
$entry1_odds_ou_5_cmp = convertOdds($entry1_odds_ou_5_cmpp, $odds_type, 0);
$overlay1_ou_5 = "0.0%";
$point_spread2_ou_5_cmp = "pk";
$entry2_odds_ou_5_cmpp = "None";
$entry2_odds_ou_5_cmp = convertOdds($entry2_odds_ou_5_cmpp, $odds_type, 0);
$overlay2_ou_5 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<form action='bet-exec1.php' method='post' class='f-wrap-100'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_5" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_5" . "<input type='hidden' name='game_desc_id' id='game_desc_id' value=" . "$game_desc_id_5" . "/><input type='hidden' name='rot_id_e1_game1' id='rot_id_e1_game1' value=" . "$entry1_rot_5" . "/><input type='hidden' name='rot_id_e2_game1' id='rot_id_e2_game1' value=" . "$entry2_rot_5" . "/></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_5" . " " . "$entry1_odds_sp_5" . "</label><input type='checkbox' name='spread_game1[]' id='testchecks' value='100odds' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_5" . " " . "$entry1_odds_pwp_5" . "</label><input type='checkbox' name='pwp_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_5" . "</label><input type='checkbox' name='ml_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_5" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_5" . "</label><input type='checkbox' name='overunder_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_5" . "</label><input type='checkbox' name='overunder_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game1' id='betbox_e1_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_5" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_5" . " " . "$entry2_odds_sp_5" . "</label><input type='checkbox' name='spread_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_5" . " " . "$entry2_odds_pwp_5" . "</label><input type='checkbox' name='pwp_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_5" . "</label><input type='checkbox' name='ml_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game1' id='betbox_e2_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_5" . "</label><input type='checkbox' name='pwp_game1[]' value='e3' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game1' id='betbox_e3_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_5" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_5" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_5_cmp" . " " . "$entry1_odds_sp_5_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_5_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_5_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_5" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_5_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_5_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_5" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_5" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_5_cmp" . " " . "$entry2_odds_sp_5_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_5_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_5_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_5" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_5" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</form>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_6 = "1:00 PM, Paul Brown Stadium, Cincinnati";
$gameNum = "6";
$game_desc_id_6 = "44";
$entry1_rot_6 = "111";
$entry1_name_6 = "Miami Dolphins";
$entry2_rot_6 = "112";
$entry2_name_6 = "Cincinnati Bengals";
$num_entries_6 = "2";
$point_spread1_sp_6 = "+3.5";
$point_spread2_sp_6 = "-3.5";
$total_pool_sp_6 = "900.0";
$entry1_pool_sp_6 = "900.0";
$entry1_odds_sp_6p = "0.0";
$entry2_pool_sp_6 = "0.0";
$entry2_odds_sp_6p = "900.0";
$max_odds_sp_6 = "900.0";
$entry1_odds_sp_6 = convertOdds($entry1_odds_sp_6p, $odds_type, $max_odds_sp_6);
$entry2_odds_sp_6 = convertOdds($entry2_odds_sp_6p, $odds_type, 0);
$point_spread1_ml_6 = "pk";
$point_spread2_ml_6 = "pk";
$total_pool_ml_6 = "1100.0";
$entry1_pool_ml_6 = "700.0";
$entry1_odds_ml_6p = "0.571428571429";
$entry2_pool_ml_6 = "400.0";
$entry2_odds_ml_6p = "1.75";
$max_odds_ml_6 = "1.75";
$entry1_odds_ml_6 = convertOdds($entry1_odds_ml_6p, $odds_type, $max_odds_ml_6);
$entry2_odds_ml_6 = convertOdds($entry2_odds_ml_6p, $odds_type, 0);
$point_spread1_pwp_6 = "+3.0";
$point_spread2_pwp_6 = "-3.0";
$total_pool_pwp_6 = "700.0";
$entry1_pool_pwp_6 = "0.0";
$entry1_odds_pwp_6p = "700.0";
$entry2_pool_pwp_6 = "700.0";
$entry2_odds_pwp_6p = "0.0";
$entry3_pool_pwp_6 = "0.0";
$entry3_odds_pwp_6p = "700.0";
$max_odds_pwp_6 = "700.0";
$entry1_odds_pwp_6 = convertOdds($entry1_odds_pwp_6p, $odds_type, 0);
$entry2_odds_pwp_6 = convertOdds($entry2_odds_pwp_6p, $odds_type, $max_odds_pwp_6);
$entry3_odds_pwp_6 = convertOdds($entry3_odds_pwp_6p, $odds_type, $max_odds_pwp_6);
$point_spread1_ou_6 = "+45.0";
$point_spread2_ou_6 = "-45.0";
$point_spread_ou_6 = "45.0";
$total_pool_ou_6 = "1200.0";
$entry1_pool_ou_6 = "1200.0";
$entry1_odds_ou_6p = "0.0";
$entry2_pool_ou_6 = "0.0";
$entry2_odds_ou_6p = "1200.0";
$max_odds_ou_6 = "1200.0";
$entry1_odds_ou_6 = convertOdds($entry1_odds_ou_6p, $odds_type, $max_odds_ou_6);
$entry2_odds_ou_6 = convertOdds($entry2_odds_ou_6p, $odds_type, 0);
$compareName_6 = "Bovada";
$point_spread1_sp_6_cmp = "pk";
$entry1_odds_sp_6_cmpp = "None";
$entry1_odds_sp_6_cmp = convertOdds($entry1_odds_sp_6_cmpp, $odds_type, 0);
$overlay1_sp_6 = "0.0%";
$point_spread2_sp_6_cmp = "pk";
$entry2_odds_sp_6_cmpp = "None";
$entry2_odds_sp_6_cmp = convertOdds($entry2_odds_sp_6_cmpp, $odds_type, 0);
$overlay2_sp_6 = "0.0%";
$point_spread1_ml_6_cmp = "pk";
$entry1_odds_ml_6_cmpp = "None";
$entry1_odds_ml_6_cmp = convertOdds($entry1_odds_ml_6_cmpp, $odds_type, 0);
$overlay1_ml_6 = "0.0%";
$point_spread2_ml_6_cmp = "pk";
$entry2_odds_ml_6_cmpp = "None";
$entry2_odds_ml_6_cmp = convertOdds($entry2_odds_ml_6_cmpp, $odds_type, 0);
$overlay2_ml_6 = "0.0%";
$point_spread1_pwp_6_cmp = "pk";
$entry1_odds_pwp_6_cmpp = "None";
$entry1_odds_pwp_6_cmp = convertOdds($entry1_odds_pwp_6_cmpp, $odds_type, 0);
$overlay1_pwp_6 = "0.0%";
$point_spread2_pwp_6_cmp = "pk";
$entry2_odds_pwp_6_cmpp = "None";
$entry2_odds_pwp_6_cmp = convertOdds($entry2_odds_pwp_6_cmpp, $odds_type, 0);
$overlay2_pwp_6 = "0.0%";
$point_spread3_pwp_6_cmp = "pk";
$entry3_odds_pwp_6_cmpp = "0.0";
$entry3_odds_pwp_6_cmp = convertOdds($entry3_odds_pwp_6_cmpp, $odds_type, 0);
$overlay3_pwp_6 = "0.0%";
$point_spread1_ou_6_cmp = "pk";
$entry1_odds_ou_6_cmpp = "None";
$entry1_odds_ou_6_cmp = convertOdds($entry1_odds_ou_6_cmpp, $odds_type, 0);
$overlay1_ou_6 = "0.0%";
$point_spread2_ou_6_cmp = "pk";
$entry2_odds_ou_6_cmpp = "None";
$entry2_odds_ou_6_cmp = convertOdds($entry2_odds_ou_6_cmpp, $odds_type, 0);
$overlay2_ou_6 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<form action='bet-exec1.php' method='post' class='f-wrap-100'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_6" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_6" . "<input type='hidden' name='game_desc_id' id='game_desc_id' value=" . "$game_desc_id_6" . "/><input type='hidden' name='rot_id_e1_game1' id='rot_id_e1_game1' value=" . "$entry1_rot_6" . "/><input type='hidden' name='rot_id_e2_game1' id='rot_id_e2_game1' value=" . "$entry2_rot_6" . "/></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_6" . " " . "$entry1_odds_sp_6" . "</label><input type='checkbox' name='spread_game1[]' id='testchecks' value='100odds' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_6" . " " . "$entry1_odds_pwp_6" . "</label><input type='checkbox' name='pwp_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_6" . "</label><input type='checkbox' name='ml_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_6" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_6" . "</label><input type='checkbox' name='overunder_game1[]' value='e1' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_6" . "</label><input type='checkbox' name='overunder_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game1' id='betbox_e1_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_6" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_6" . " " . "$entry2_odds_sp_6" . "</label><input type='checkbox' name='spread_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_6" . " " . "$entry2_odds_pwp_6" . "</label><input type='checkbox' name='pwp_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_6" . "</label><input type='checkbox' name='ml_game1[]' value='e2' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game1' id='betbox_e2_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_6" . "</label><input type='checkbox' name='pwp_game1[]' value='e3' onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game1' id='betbox_e3_game1' type='text' onchange='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_6" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_6" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_6_cmp" . " " . "$entry1_odds_sp_6_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_6_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_6_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_6" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_6_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_6_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_6" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_6" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_6_cmp" . " " . "$entry2_odds_sp_6_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_6_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_6_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_6" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_6" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</form>\n";
echo "</div>\n";
echo "<hr />\n";
?>
