<?php
session_start();
require 'odd_funcs.php';
$gamename = "1:00 Pick 6 - Sun, Oct 7, 2012";
$entry1_rot_game1 = "103";
$entry1_name_game1 = "ATL";
$entry2_rot_game1 = "104";
$entry2_name_game1 = "WAS";
$pwp_spread_game1 = "3.0";
$pwp_favorite_game1 = "103";
$point_spread1_game1 = " -3";
$point_spread2_game1 = "";
$entry1_rot_game2 = "101";
$entry1_name_game2 = "PHI";
$entry2_rot_game2 = "102";
$entry2_name_game2 = "PIT";
$pwp_spread_game2 = "3.0";
$pwp_favorite_game2 = "102";
$point_spread1_game2 = "";
$point_spread2_game2 = " -3";
$entry1_rot_game3 = "105";
$entry1_name_game3 = "GNB";
$entry2_rot_game3 = "106";
$entry2_name_game3 = "IND";
$pwp_spread_game3 = "7.0";
$pwp_favorite_game3 = "105";
$point_spread1_game3 = " -7";
$point_spread2_game3 = "";
$entry1_rot_game4 = "107";
$entry1_name_game4 = "CLE";
$entry2_rot_game4 = "108";
$entry2_name_game4 = "NYG";
$pwp_spread_game4 = "9.0";
$pwp_favorite_game4 = "108";
$point_spread1_game4 = "";
$point_spread2_game4 = " -9";
$entry1_rot_game5 = "109";
$entry1_name_game5 = "TEN";
$entry2_rot_game5 = "110";
$entry2_name_game5 = "MIN";
$pwp_spread_game5 = "6.0";
$pwp_favorite_game5 = "110";
$point_spread1_game5 = "";
$point_spread2_game5 = " -6";
$entry1_rot_game6 = "111";
$entry1_name_game6 = "MIA";
$entry2_rot_game6 = "112";
$entry2_name_game6 = "CIN";
$pwp_spread_game6 = "3.0";
$pwp_favorite_game6 = "112";
$point_spread1_game6 = "";
$point_spread2_game6 = " -3";
$carryover = "24000.0";
$total_pool_p6 = "7463.0";
$entry1_pick_game1 = "ATL";
$entry2_pick_game1 = "PHI";
$entry3_pick_game1 = "IND";
$entry4_pick_game1 = "NYG";
$entry5_pick_game1 = "MIN";
$entry6_pick_game1 = "CIN";
$odds_game1 = "48.0986842105";
$entry1_pick_game2 = "WAS";
$entry2_pick_game2 = "PHI";
$entry3_pick_game2 = "PUSH";
$entry4_pick_game2 = "CLE";
$entry5_pick_game2 = "MIN";
$entry6_pick_game2 = "MIA";
$odds_game2 = "7462.0";
$entry1_pick_game3 = "ATL";
$entry2_pick_game3 = "PHI";
$entry3_pick_game3 = "GNB";
$entry4_pick_game3 = "CLE";
$entry5_pick_game3 = "TEN";
$entry6_pick_game3 = "MIA";
$odds_game3 = "25.0944055944";
$entry1_pick_game4 = "ATL";
$entry2_pick_game4 = "PIT";
$entry3_pick_game4 = "IND";
$entry4_pick_game4 = "CLE";
$entry5_pick_game4 = "MIN";
$entry6_pick_game4 = "CIN";
$odds_game4 = "438.0";
$entry1_pick_game5 = "WAS";
$entry2_pick_game5 = "PHI";
$entry3_pick_game5 = "IND";
$entry4_pick_game5 = "NYG";
$entry5_pick_game5 = "TEN";
$entry6_pick_game5 = "MIA";
$odds_game5 = "157.787234043";
echo "<div id='pool_view'>\n";
echo "<table id='hor-minimalist-a' summary='Pick 6 Current Odds'>\n";
echo "<colgroup>\n";
echo "<col />\n";
echo "<col />\n";
echo "<col />\n";
echo "<col />\n";
echo "<col />\n";
echo "<col />\n";
echo "<col class='oce-first' />\n";
echo "</colgroup>\n";
echo "<thead>\n";
echo "<tr>\n";
echo "<th colspan='7'><span>" . "$gamename" . "&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Carryover: $" . "$carryover" . "</span></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th scope='col'>" . "$entry1_name_game1" . "$point_spread1_game1" . "<br />" . "$entry2_name_game1" . "$point_spread2_game1" . "</th>\n";
echo "<th scope='col'>" . "$entry1_name_game2" . "$point_spread1_game2" . "<br />" . "$entry2_name_game2" . "$point_spread2_game2" . "</th>\n";
echo "<th scope='col'>" . "$entry1_name_game3" . "$point_spread1_game3" . "<br />" . "$entry2_name_game3" . "$point_spread2_game3" . "</th>\n";
echo "<th scope='col'>" . "$entry1_name_game4" . "$point_spread1_game4" . "<br />" . "$entry2_name_game4" . "$point_spread2_game4" . "</th>\n";
echo "<th scope='col'>" . "$entry1_name_game5" . "$point_spread1_game5" . "<br />" . "$entry2_name_game5" . "$point_spread2_game5" . "</th>\n";
echo "<th scope='col'>" . "$entry1_name_game6" . "$point_spread1_game6" . "<br />" . "$entry2_name_game6" . "$point_spread2_game6" . "</th>\n";
echo "<th scope='col'>Current<br />Odds</th>\n";
echo "</tr>\n";
echo "</thead>\n";
echo "<tbody>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_pick_game1" . "</td>\n";
echo "<td>" . "$entry2_pick_game1" . "</td>\n";
echo "<td>" . "$entry3_pick_game1" . "</td>\n";
echo "<td>" . "$entry4_pick_game1" . "</td>\n";
echo "<td>" . "$entry5_pick_game1" . "</td>\n";
echo "<td>" . "$entry6_pick_game1" . "</td>\n";
echo "<td>" . sprintf_nbsp("%'#10.2f", $odds_game1) . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_pick_game2" . "</td>\n";
echo "<td>" . "$entry2_pick_game2" . "</td>\n";
echo "<td>" . "$entry3_pick_game2" . "</td>\n";
echo "<td>" . "$entry4_pick_game2" . "</td>\n";
echo "<td>" . "$entry5_pick_game2" . "</td>\n";
echo "<td>" . "$entry6_pick_game2" . "</td>\n";
echo "<td>" . sprintf_nbsp("%'#10.2f", $odds_game2) . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_pick_game3" . "</td>\n";
echo "<td>" . "$entry2_pick_game3" . "</td>\n";
echo "<td>" . "$entry3_pick_game3" . "</td>\n";
echo "<td>" . "$entry4_pick_game3" . "</td>\n";
echo "<td>" . "$entry5_pick_game3" . "</td>\n";
echo "<td>" . "$entry6_pick_game3" . "</td>\n";
echo "<td>" . sprintf_nbsp("%'#10.2f", $odds_game3) . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_pick_game4" . "</td>\n";
echo "<td>" . "$entry2_pick_game4" . "</td>\n";
echo "<td>" . "$entry3_pick_game4" . "</td>\n";
echo "<td>" . "$entry4_pick_game4" . "</td>\n";
echo "<td>" . "$entry5_pick_game4" . "</td>\n";
echo "<td>" . "$entry6_pick_game4" . "</td>\n";
echo "<td>" . sprintf_nbsp("%'#10.2f", $odds_game4) . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_pick_game5" . "</td>\n";
echo "<td>" . "$entry2_pick_game5" . "</td>\n";
echo "<td>" . "$entry3_pick_game5" . "</td>\n";
echo "<td>" . "$entry4_pick_game5" . "</td>\n";
echo "<td>" . "$entry5_pick_game5" . "</td>\n";
echo "<td>" . "$entry6_pick_game5" . "</td>\n";
echo "<td>" . sprintf_nbsp("%'#10.2f", $odds_game5) . "</td>\n";
echo "</tr>\n";
echo "</tbody>\n";
echo "</table>\n";
echo "<br />\n";
echo "</div>\n";
?>
