<?php
session_start();
require 'odd_funcs.php';
$gamedate = "Sunday, October 07, 2012";
if(!isset($_SESSION["SESS_MEMBER_ID"]) || (trim($_SESSION["SESS_MEMBER_ID"]) == ""))
{
$colspan_gameday = "7";
$colspan_header = "4";
$betheader_id = "olPercent2_nd";
$betheadergame_id = "betBoxHeaderHeader_nd";
$bets_disabled = "DISABLED";
}
else
{
$colspan_gameday = "8";
$colspan_header = "5";
$betheader_id = "olPercent2";
$betheadergame_id = "betBoxHeaderHeader";
$bets_disabled = "";
}
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan=" . "$colspan_gameday" . "; id='gameDate'>" . "$gamedate" . "</th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rotHeader'>Rot</th>\n";
echo "<th id='teamNameHeader'>Team</th>\n";
echo "<th id='pointSpreadHeader'>Point Spread</th>\n";
echo "<th id='pointSpreadHeader'>PWP</th>\n";
echo "<th id='pointSpreadHeader'>Moneyline</th>\n";
echo "<th id='ouHeaderLeftHeader'></th>\n";
echo "<th id='ouHeaderRightHeader'>Total</th>\n";
echo "<th id=" . "$betheadergame_id" . ">Amount</th>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<br />\n";
if(isset($_COOKIE["ppkDisplayOdds"]))
{
$odds_type = intval($_COOKIE["ppkDisplayOdds"]);
}
else
{
$odds_type = 0;
}
$total_games = 0;
echo "<form name='bform' action='bet-exec2.php' onsubmit='return validateBetForm(" . $_SESSION['SESS_BALANCE'] . ")' method='post' class='f-wrap-100'>\n";
$gamename_1 = "1:00 PM EDT, FedEx Field, Landover";
$gamename_1_p = str_replace(" ", "_", "1:00 PM EDT, FedEx Field, Landover");
$gameNum = "1";
$game_desc_id_1 = "40";
$total_games++;
$entry1_rot_1 = "103";
$entry1_name_1 = "Atlanta Falcons";
$entry1_name_1_p = str_replace(" ", "_", "Atlanta Falcons");
$entry2_rot_1 = "104";
$entry2_name_1 = "Washington Redskins";
$entry2_name_1_p = str_replace(" ", "_", "Washington Redskins");
$entry3_rot_1 = "3";
$entry1_rot_1_ou = "1";
$entry2_rot_1_ou = "2";
$gamename2_1 = "Atlanta Falcons at Washington Redskins";
$gamename2_1_p = str_replace(" ", "_", "Atlanta Falcons at Washington Redskins");
$gamedate2_1 = "07_Oct_2012";
$num_entries_1 = "2";
$pool_id_sp_1 = "120";
$point_spread1_sp_1 = "-3.0";
$point_spread2_sp_1 = "+3.0";
$total_pool_sp_1 = "10903.0";
$acct_id_sp_1 = "3166";
$pool_size_sp_1 = "10903.0";
$entry1_pool_sp_1 = "2625.0";
$entry1_odds_sp_1p = "3.15352380952";
$entry2_pool_sp_1 = "3322.0";
$entry2_odds_sp_1p = "2.2820590006";
$max_odds_sp_1 = "3.15352380952";
$entry1_odds_sp_1 = convertOdds($entry1_odds_sp_1p, $odds_type, 0);
$entry2_odds_sp_1 = convertOdds($entry2_odds_sp_1p, $odds_type, $max_odds_sp_1);
$pool_id_ml_1 = "121";
$point_spread1_ml_1 = "pk";
$point_spread2_ml_1 = "pk";
$total_pool_ml_1 = "2866.0";
$acct_id_ml_1 = "3167";
$pool_size_ml_1 = "2866.0";
$entry1_pool_ml_1 = "1451.0";
$entry1_odds_ml_1p = "0.975189524466";
$entry2_pool_ml_1 = "1415.0";
$entry2_odds_ml_1p = "1.02544169611";
$max_odds_ml_1 = "1.02544169611";
$entry1_odds_ml_1 = convertOdds($entry1_odds_ml_1p, $odds_type, $max_odds_ml_1);
$entry2_odds_ml_1 = convertOdds($entry2_odds_ml_1p, $odds_type, 0);
$pool_id_pwp_1 = "122";
$point_spread1_pwp_1 = "-3.0";
$point_spread2_pwp_1 = "+3.0";
$point_spread3_pwp_1 = "+3.0,Atlanta_Falcons";
$total_pool_pwp_1 = "631.0";
$acct_id_pwp_1 = "3168";
$pool_size_pwp_1 = "631.0";
$entry1_pool_pwp_1 = "603.0";
$entry1_odds_pwp_1p = "0.0464344941957";
$entry2_pool_pwp_1 = "14.0";
$entry2_odds_pwp_1p = "44.0714285714";
$entry3_pool_pwp_1 = "14.0";
$entry3_odds_pwp_1p = "44.0714285714";
$max_odds_pwp_1 = "44.0714285714";
$entry1_odds_pwp_1 = convertOdds($entry1_odds_pwp_1p, $odds_type, $max_odds_pwp_1);
$entry2_odds_pwp_1 = convertOdds($entry2_odds_pwp_1p, $odds_type, 0);
$entry3_odds_pwp_1 = convertOdds($entry3_odds_pwp_1p, $odds_type, $max_odds_pwp_1);
$pool_id_ou_1 = "123";
$point_spread1_ou_1 = "+51.0";
$point_spread2_ou_1 = "+51.0";
$point_spread_ou_1 = "51.0";
$total_pool_ou_1 = "910.0";
$acct_id_ou_1 = "3169";
$pool_size_ou_1 = "910.0";
$entry1_pool_ou_1 = "6.0";
$entry1_odds_ou_1p = "150.666666667";
$entry2_pool_ou_1 = "904.0";
$entry2_odds_ou_1p = "0.00663716814159";
$max_odds_ou_1 = "150.666666667";
$entry1_odds_ou_1 = convertOdds($entry1_odds_ou_1p, $odds_type, 0);
$entry2_odds_ou_1 = convertOdds($entry2_odds_ou_1p, $odds_type, $max_odds_ou_1);
$compareName_1 = "Bovada";
$point_spread1_sp_1_cmp = "-3.0";
$entry1_odds_sp_1_cmpp = "0.909091";
$entry1_odds_sp_1_cmp = convertOdds($entry1_odds_sp_1_cmpp, 3 + $odds_type, 0);
$overlay1_sp_1 = "246.9%";
$point_spread2_sp_1_cmp = "+3.0";
$entry2_odds_sp_1_cmpp = "0.909091";
$entry2_odds_sp_1_cmp = convertOdds($entry2_odds_sp_1_cmpp, 3 + $odds_type, 0);
$overlay2_sp_1 = "151.0%";
$point_spread1_ml_1_cmp = "pk";
$entry1_odds_ml_1_cmpp = "1.3";
$entry1_odds_ml_1_cmp = convertOdds($entry1_odds_ml_1_cmpp, 3 + $odds_type, 0);
$overlay1_ml_1 = "-25.0%";
$point_spread2_ml_1_cmp = "pk";
$entry2_odds_ml_1_cmpp = "0.666667";
$entry2_odds_ml_1_cmp = convertOdds($entry2_odds_ml_1_cmpp, 3 + $odds_type, 0);
$overlay2_ml_1 = "53.8%";
$point_spread1_pwp_1_cmp = "-3.0";
$entry1_odds_pwp_1_cmpp = "0.909091";
$entry1_odds_pwp_1_cmp = convertOdds($entry1_odds_pwp_1_cmpp, 3 + $odds_type, 0);
$overlay1_pwp_1 = "-94.9%";
$point_spread2_pwp_1_cmp = "+3.0";
$entry2_odds_pwp_1_cmpp = "0.909091";
$entry2_odds_pwp_1_cmp = convertOdds($entry2_odds_pwp_1_cmpp, 3 + $odds_type, 0);
$overlay2_pwp_1 = "4747.9%";
$point_spread3_pwp_1_cmp = "pk";
$entry3_odds_pwp_1_cmpp = "0.0";
$entry3_odds_pwp_1_cmp = convertOdds($entry3_odds_pwp_1_cmpp, 3 + $odds_type, 0);
$overlay3_pwp_1 = "0.0%";
$point_spread1_ou_1_cmp = "+52.0";
$entry1_odds_ou_1_cmpp = "0.909091";
$entry1_odds_ou_1_cmp = convertOdds($entry1_odds_ou_1_cmpp, 3 + $odds_type, 0);
$overlay1_ou_1 = "16473%";
$point_spread2_ou_1_cmp = "+52.0";
$entry2_odds_ou_1_cmpp = "0.909091";
$entry2_odds_ou_1_cmp = convertOdds($entry2_odds_ou_1_cmpp, 3 + $odds_type, 0);
$overlay2_ou_1 = "-99.3%";
echo "<div id='pool_view'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_1" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'><input type='hidden' name='gamename_arr[]' value=" . "$gamename_1_p" . " /><input type='hidden' name='gamename2_arr[]' value=" . "$gamename2_1_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='entry1_name_arr[]' value=" . "$entry1_name_1_p" . " /><input type='hidden' name='entry2_name_arr[]' value=" . "$entry2_name_1_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='gamedate_arr[]' value=" . "$gamedate" . " /></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_sp_1" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_sp_1" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ml_1" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ml_1" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_pwp_1" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_pwp_1" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ou_1" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ou_1" . " />\n";
echo "<td>" . "$entry1_rot_1" . "<input type='hidden' name='game_desc_id_arr[]' id='game_desc_id' value=" . "$game_desc_id_1" . " /><input type='hidden' name='rot_id_e1_game1' id='rot_id_e1_game1' value=" . "$entry1_rot_1" . " /><input type='hidden' name='rot_id_e2_game1' id='rot_id_e2_game1' value=" . "$entry2_rot_1" . " /><input type='hidden' name='rot_id_e3_game1' id='rot_id_e3_game1' value=" . "$entry3_rot_1" . " /></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_1" . "<input type='hidden' name='game_num_arr[]' value='1'" . " /><input type='hidden' name='acct_id_sp[]' value=" . "$acct_id_sp_1" . " /><input type='hidden' name='acct_id_pwp[]' value=" . "$acct_id_pwp_1" . " /><input type='hidden' name='acct_id_ml[]' value=" . "$acct_id_ml_1" . " /><input type='hidden' name='acct_id_ou[]' value=" . "$acct_id_ou_1" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_1" . " " . "$entry1_odds_sp_1" . "</label><input type='checkbox' name='spread_game1[]' id='cb_sp_e1_g1' value=" . "$entry1_rot_1" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_1" . " " . "$entry1_odds_pwp_1" . "</label><input type='checkbox' name='pwp_game1[]' id='cb_pwp_e1_g1' value=" . "$entry1_rot_1" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_1" . "</label><input type='checkbox' name='ml_game1[]' id='cb_ml_e1_g1' value=" . "$entry1_rot_1" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_1" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_1" . "</label><input type='checkbox' name='overunder_game1[]' id='cb_ou_e1_g1' value=" . "$entry1_rot_1_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_1" . "</label><input type='checkbox' name='overunder_game1[]' id='cb_ou_e2_g1' value=" . "$entry2_rot_1_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game1' id='betbox_e1_game1' type='text' onclick='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_1" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_1" . " " . "$entry2_odds_sp_1" . "</label><input type='checkbox' name='spread_game1[]' id='cb_sp_e2_g1' value=" . "$entry2_rot_1" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_1" . " " . "$entry2_odds_pwp_1" . "</label><input type='checkbox' name='pwp_game1[]' id='cb_pwp_e2_g1' value=" . "$entry2_rot_1" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_1" . "</label><input type='checkbox' name='ml_game1[]' id='cb_ml_e2_g1' value=" . "$entry2_rot_1" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game1' id='betbox_e2_game1' type='text' onclick='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td><input type='hidden' name='point_spread1_sp_1' value= " . "$point_spread1_sp_1" . " /><input type='hidden' name='point_spread2_sp_1' value= " . "$point_spread2_sp_1" . " /><input type='hidden' name='point_spread1_pwp_1' value= " . "$point_spread1_pwp_1" . " /><input type='hidden' name='point_spread2_pwp_1' value= " . "$point_spread2_pwp_1" . " /><input type='hidden' name='point_spread3_pwp_1' value= " . "$point_spread3_pwp_1" . " /><input type='hidden' name='point_spread1_ou_1' value= " . "$point_spread1_ou_1" . " /><input type='hidden' name='point_spread2_ou_1' value= " . "$point_spread2_ou_1" . " /></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_1" . "</label><input type='checkbox' name='pwp_game1[]' id='cb_pwp_e3_g1' value=" . "$entry3_rot_1" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game1' id='betbox_e3_game1' type='text' onclick='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<input type='hidden' name='entry1_odds_sp_arr[]' value=" . "$entry1_odds_sp_1p" . " /><input type='hidden' name='entry2_odds_sp_arr[]' value=" . "$entry2_odds_sp_1p" . " />\n";
echo "<input type='hidden' name='entry1_odds_pwp_arr[]' value=" . "$entry1_odds_pwp_1p" . " /><input type='hidden' name='entry2_odds_pwp_arr[]' value=" . "$entry2_odds_pwp_1p" . " /><input type='hidden' name='entry3_odds_pwp_arr[]' value=" . "$entry3_odds_pwp_1p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ml_arr[]' value=" . "$entry1_odds_ml_1p" . " /><input type='hidden' name='entry2_odds_ml_arr[]' value=" . "$entry2_odds_ml_1p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ou_arr[]' value=" . "$entry1_odds_ou_1p" . " /><input type='hidden' name='entry2_odds_ou_arr[]' value=" . "$entry2_odds_ou_1p" . " />\n";
echo "<input type='hidden' name='pool_size_sp_game1' id='pool_size_sp_game1' value=" . "$pool_size_sp_1" . " />\n";
echo "<input type='hidden' name='pool_size_pwp_game1' id='pool_size_pwp_game1' value=" . "$pool_size_pwp_1" . " />\n";
echo "<input type='hidden' name='pool_size_ml_game1' id='pool_size_ml_game1' value=" . "$pool_size_ml_1" . " />\n";
echo "<input type='hidden' name='pool_size_ou_game1' id='pool_size_ou_game1' value=" . "$pool_size_ou_1" . " />\n";
echo "<input type='hidden' name='rot_id_e1_game1_ou' id='rot_id_e1_game1_ou' value=" . "$entry1_rot_1_ou" . " /><input type='hidden' name='rot_id_e2_game1_ou' id='rot_id_e2_game1_ou' value=" . "$entry2_rot_1_ou" . " />\n";
echo "<input type='hidden' name='gamedate2_arr[]' value=" . "$gamedate2_1" . " />\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_1" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_1" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_1_cmp" . " " . "$entry1_odds_sp_1_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_1_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_1_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_1" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_1_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_1_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_1" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_1" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_1_cmp" . " " . "$entry2_odds_sp_1_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_1_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_1" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_1_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_1" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_1" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_2 = "1:00 PM EDT, Heinz Field, Pittsburgh";
$gamename_2_p = str_replace(" ", "_", "1:00 PM EDT, Heinz Field, Pittsburgh");
$gameNum = "2";
$game_desc_id_2 = "39";
$total_games++;
$entry1_rot_2 = "101";
$entry1_name_2 = "Philadelphia Eagles";
$entry1_name_2_p = str_replace(" ", "_", "Philadelphia Eagles");
$entry2_rot_2 = "102";
$entry2_name_2 = "Pittsburgh Steelers";
$entry2_name_2_p = str_replace(" ", "_", "Pittsburgh Steelers");
$entry3_rot_2 = "3";
$entry1_rot_2_ou = "1";
$entry2_rot_2_ou = "2";
$gamename2_2 = "Philadelphia Eagles at Pittsburgh Steelers";
$gamename2_2_p = str_replace(" ", "_", "Philadelphia Eagles at Pittsburgh Steelers");
$gamedate2_2 = "07_Oct_2012";
$num_entries_2 = "2";
$pool_id_sp_2 = "116";
$point_spread1_sp_2 = "+3.5";
$point_spread2_sp_2 = "-3.5";
$total_pool_sp_2 = "3700.0";
$acct_id_sp_2 = "3162";
$pool_size_sp_2 = "3700.0";
$entry1_pool_sp_2 = "3300.0";
$entry1_odds_sp_2p = "0.121212121212";
$entry2_pool_sp_2 = "400.0";
$entry2_odds_sp_2p = "8.25";
$max_odds_sp_2 = "8.25";
$entry1_odds_sp_2 = convertOdds($entry1_odds_sp_2p, $odds_type, $max_odds_sp_2);
$entry2_odds_sp_2 = convertOdds($entry2_odds_sp_2p, $odds_type, 0);
$pool_id_ml_2 = "117";
$point_spread1_ml_2 = "pk";
$point_spread2_ml_2 = "pk";
$total_pool_ml_2 = "1903.0";
$acct_id_ml_2 = "3163";
$pool_size_ml_2 = "1903.0";
$entry1_pool_ml_2 = "1100.0";
$entry1_odds_ml_2p = "0.73";
$entry2_pool_ml_2 = "803.0";
$entry2_odds_ml_2p = "1.3698630137";
$max_odds_ml_2 = "1.3698630137";
$entry1_odds_ml_2 = convertOdds($entry1_odds_ml_2p, $odds_type, $max_odds_ml_2);
$entry2_odds_ml_2 = convertOdds($entry2_odds_ml_2p, $odds_type, 0);
$pool_id_pwp_2 = "118";
$point_spread1_pwp_2 = "+3.0";
$point_spread2_pwp_2 = "-3.0";
$point_spread3_pwp_2 = "+3.0,Philadelphia_Eagles";
$total_pool_pwp_2 = "1903.0";
$acct_id_pwp_2 = "3164";
$pool_size_pwp_2 = "1903.0";
$entry1_pool_pwp_2 = "1002.0";
$entry1_odds_pwp_2p = "0.899201596806";
$entry2_pool_pwp_2 = "1.0";
$entry2_odds_pwp_2p = "1902.0";
$entry3_pool_pwp_2 = "900.0";
$entry3_odds_pwp_2p = "1.11444444444";
$max_odds_pwp_2 = "1902.0";
$entry1_odds_pwp_2 = convertOdds($entry1_odds_pwp_2p, $odds_type, $max_odds_pwp_2);
$entry2_odds_pwp_2 = convertOdds($entry2_odds_pwp_2p, $odds_type, 0);
$entry3_odds_pwp_2 = convertOdds($entry3_odds_pwp_2p, $odds_type, $max_odds_pwp_2);
$pool_id_ou_2 = "119";
$point_spread1_ou_2 = "+43.5";
$point_spread2_ou_2 = "+43.5";
$point_spread_ou_2 = "43.5";
$total_pool_ou_2 = "1928.0";
$acct_id_ou_2 = "3165";
$pool_size_ou_2 = "1928.0";
$entry1_pool_ou_2 = "1005.0";
$entry1_odds_ou_2p = "0.918407960199";
$entry2_pool_ou_2 = "923.0";
$entry2_odds_ou_2p = "1.08884073673";
$max_odds_ou_2 = "1.08884073673";
$entry1_odds_ou_2 = convertOdds($entry1_odds_ou_2p, $odds_type, $max_odds_ou_2);
$entry2_odds_ou_2 = convertOdds($entry2_odds_ou_2p, $odds_type, 0);
$compareName_2 = "Bovada";
$point_spread1_sp_2_cmp = "pk";
$entry1_odds_sp_2_cmpp = "None";
$entry1_odds_sp_2_cmp = convertOdds($entry1_odds_sp_2_cmpp, 3 + $odds_type, 0);
$overlay1_sp_2 = "0.0%";
$point_spread2_sp_2_cmp = "pk";
$entry2_odds_sp_2_cmpp = "None";
$entry2_odds_sp_2_cmp = convertOdds($entry2_odds_sp_2_cmpp, 3 + $odds_type, 0);
$overlay2_sp_2 = "0.0%";
$point_spread1_ml_2_cmp = "pk";
$entry1_odds_ml_2_cmpp = "None";
$entry1_odds_ml_2_cmp = convertOdds($entry1_odds_ml_2_cmpp, 3 + $odds_type, 0);
$overlay1_ml_2 = "0.0%";
$point_spread2_ml_2_cmp = "pk";
$entry2_odds_ml_2_cmpp = "None";
$entry2_odds_ml_2_cmp = convertOdds($entry2_odds_ml_2_cmpp, 3 + $odds_type, 0);
$overlay2_ml_2 = "0.0%";
$point_spread1_pwp_2_cmp = "pk";
$entry1_odds_pwp_2_cmpp = "None";
$entry1_odds_pwp_2_cmp = convertOdds($entry1_odds_pwp_2_cmpp, 3 + $odds_type, 0);
$overlay1_pwp_2 = "0.0%";
$point_spread2_pwp_2_cmp = "pk";
$entry2_odds_pwp_2_cmpp = "None";
$entry2_odds_pwp_2_cmp = convertOdds($entry2_odds_pwp_2_cmpp, 3 + $odds_type, 0);
$overlay2_pwp_2 = "0.0%";
$point_spread3_pwp_2_cmp = "pk";
$entry3_odds_pwp_2_cmpp = "0.0";
$entry3_odds_pwp_2_cmp = convertOdds($entry3_odds_pwp_2_cmpp, 3 + $odds_type, 0);
$overlay3_pwp_2 = "0.0%";
$point_spread1_ou_2_cmp = "pk";
$entry1_odds_ou_2_cmpp = "None";
$entry1_odds_ou_2_cmp = convertOdds($entry1_odds_ou_2_cmpp, 3 + $odds_type, 0);
$overlay1_ou_2 = "0.0%";
$point_spread2_ou_2_cmp = "pk";
$entry2_odds_ou_2_cmpp = "None";
$entry2_odds_ou_2_cmp = convertOdds($entry2_odds_ou_2_cmpp, 3 + $odds_type, 0);
$overlay2_ou_2 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_2" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'><input type='hidden' name='gamename_arr[]' value=" . "$gamename_2_p" . " /><input type='hidden' name='gamename2_arr[]' value=" . "$gamename2_2_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='entry1_name_arr[]' value=" . "$entry1_name_2_p" . " /><input type='hidden' name='entry2_name_arr[]' value=" . "$entry2_name_2_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='gamedate_arr[]' value=" . "$gamedate" . " /></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_sp_2" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_sp_2" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ml_2" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ml_2" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_pwp_2" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_pwp_2" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ou_2" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ou_2" . " />\n";
echo "<td>" . "$entry1_rot_2" . "<input type='hidden' name='game_desc_id_arr[]' id='game_desc_id' value=" . "$game_desc_id_2" . " /><input type='hidden' name='rot_id_e1_game2' id='rot_id_e1_game2' value=" . "$entry1_rot_2" . " /><input type='hidden' name='rot_id_e2_game2' id='rot_id_e2_game2' value=" . "$entry2_rot_2" . " /><input type='hidden' name='rot_id_e3_game2' id='rot_id_e3_game2' value=" . "$entry3_rot_2" . " /></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_2" . "<input type='hidden' name='game_num_arr[]' value='2'" . " /><input type='hidden' name='acct_id_sp[]' value=" . "$acct_id_sp_2" . " /><input type='hidden' name='acct_id_pwp[]' value=" . "$acct_id_pwp_2" . " /><input type='hidden' name='acct_id_ml[]' value=" . "$acct_id_ml_2" . " /><input type='hidden' name='acct_id_ou[]' value=" . "$acct_id_ou_2" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_2" . " " . "$entry1_odds_sp_2" . "</label><input type='checkbox' name='spread_game2[]' id='cb_sp_e1_g2' value=" . "$entry1_rot_2" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_2" . " " . "$entry1_odds_pwp_2" . "</label><input type='checkbox' name='pwp_game2[]' id='cb_pwp_e1_g2' value=" . "$entry1_rot_2" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_2" . "</label><input type='checkbox' name='ml_game2[]' id='cb_ml_e1_g2' value=" . "$entry1_rot_2" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_2" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_2" . "</label><input type='checkbox' name='overunder_game2[]' id='cb_ou_e1_g2' value=" . "$entry1_rot_2_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_2" . "</label><input type='checkbox' name='overunder_game2[]' id='cb_ou_e2_g2' value=" . "$entry2_rot_2_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game2' id='betbox_e1_game2' type='text' onclick='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_2" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_2" . " " . "$entry2_odds_sp_2" . "</label><input type='checkbox' name='spread_game2[]' id='cb_sp_e2_g2' value=" . "$entry2_rot_2" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_2" . " " . "$entry2_odds_pwp_2" . "</label><input type='checkbox' name='pwp_game2[]' id='cb_pwp_e2_g2' value=" . "$entry2_rot_2" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_2" . "</label><input type='checkbox' name='ml_game2[]' id='cb_ml_e2_g2' value=" . "$entry2_rot_2" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game2' id='betbox_e2_game2' type='text' onclick='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td><input type='hidden' name='point_spread1_sp_2' value= " . "$point_spread1_sp_2" . " /><input type='hidden' name='point_spread2_sp_2' value= " . "$point_spread2_sp_2" . " /><input type='hidden' name='point_spread1_pwp_2' value= " . "$point_spread1_pwp_2" . " /><input type='hidden' name='point_spread2_pwp_2' value= " . "$point_spread2_pwp_2" . " /><input type='hidden' name='point_spread3_pwp_2' value= " . "$point_spread3_pwp_2" . " /><input type='hidden' name='point_spread1_ou_2' value= " . "$point_spread1_ou_2" . " /><input type='hidden' name='point_spread2_ou_2' value= " . "$point_spread2_ou_2" . " /></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_2" . "</label><input type='checkbox' name='pwp_game2[]' id='cb_pwp_e3_g2' value=" . "$entry3_rot_2" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game2' id='betbox_e3_game2' type='text' onclick='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<input type='hidden' name='entry1_odds_sp_arr[]' value=" . "$entry1_odds_sp_2p" . " /><input type='hidden' name='entry2_odds_sp_arr[]' value=" . "$entry2_odds_sp_2p" . " />\n";
echo "<input type='hidden' name='entry1_odds_pwp_arr[]' value=" . "$entry1_odds_pwp_2p" . " /><input type='hidden' name='entry2_odds_pwp_arr[]' value=" . "$entry2_odds_pwp_2p" . " /><input type='hidden' name='entry3_odds_pwp_arr[]' value=" . "$entry3_odds_pwp_2p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ml_arr[]' value=" . "$entry1_odds_ml_2p" . " /><input type='hidden' name='entry2_odds_ml_arr[]' value=" . "$entry2_odds_ml_2p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ou_arr[]' value=" . "$entry1_odds_ou_2p" . " /><input type='hidden' name='entry2_odds_ou_arr[]' value=" . "$entry2_odds_ou_2p" . " />\n";
echo "<input type='hidden' name='pool_size_sp_game2' id='pool_size_sp_game2' value=" . "$pool_size_sp_2" . " />\n";
echo "<input type='hidden' name='pool_size_pwp_game2' id='pool_size_pwp_game2' value=" . "$pool_size_pwp_2" . " />\n";
echo "<input type='hidden' name='pool_size_ml_game2' id='pool_size_ml_game2' value=" . "$pool_size_ml_2" . " />\n";
echo "<input type='hidden' name='pool_size_ou_game2' id='pool_size_ou_game2' value=" . "$pool_size_ou_2" . " />\n";
echo "<input type='hidden' name='rot_id_e1_game2_ou' id='rot_id_e1_game2_ou' value=" . "$entry1_rot_2_ou" . " /><input type='hidden' name='rot_id_e2_game2_ou' id='rot_id_e2_game2_ou' value=" . "$entry2_rot_2_ou" . " />\n";
echo "<input type='hidden' name='gamedate2_arr[]' value=" . "$gamedate2_2" . " />\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_2" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_2" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_2_cmp" . " " . "$entry1_odds_sp_2_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_2_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_2_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_2" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_2_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_2_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_2" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_2" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_2_cmp" . " " . "$entry2_odds_sp_2_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_2_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_2" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_2_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_2" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_2" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_3 = "1:00 PM EDT, Lucas Oil Stadium, Indianapolis";
$gamename_3_p = str_replace(" ", "_", "1:00 PM EDT, Lucas Oil Stadium, Indianapolis");
$gameNum = "3";
$game_desc_id_3 = "41";
$total_games++;
$entry1_rot_3 = "105";
$entry1_name_3 = "Green Bay Packers";
$entry1_name_3_p = str_replace(" ", "_", "Green Bay Packers");
$entry2_rot_3 = "106";
$entry2_name_3 = "Indianapolis Colts";
$entry2_name_3_p = str_replace(" ", "_", "Indianapolis Colts");
$entry3_rot_3 = "3";
$entry1_rot_3_ou = "1";
$entry2_rot_3_ou = "2";
$gamename2_3 = "Green Bay Packers at Indianapolis Colts";
$gamename2_3_p = str_replace(" ", "_", "Green Bay Packers at Indianapolis Colts");
$gamedate2_3 = "07_Oct_2012";
$num_entries_3 = "2";
$pool_id_sp_3 = "124";
$point_spread1_sp_3 = "-7.0";
$point_spread2_sp_3 = "+7.0";
$total_pool_sp_3 = "5004.0";
$acct_id_sp_3 = "3170";
$pool_size_sp_3 = "5004.0";
$entry1_pool_sp_3 = "1703.0";
$entry1_odds_sp_3p = "1.93834409865";
$entry2_pool_sp_3 = "3301.0";
$entry2_odds_sp_3p = "0.515904271433";
$max_odds_sp_3 = "1.93834409865";
$entry1_odds_sp_3 = convertOdds($entry1_odds_sp_3p, $odds_type, 0);
$entry2_odds_sp_3 = convertOdds($entry2_odds_sp_3p, $odds_type, $max_odds_sp_3);
$pool_id_ml_3 = "125";
$point_spread1_ml_3 = "pk";
$point_spread2_ml_3 = "pk";
$total_pool_ml_3 = "1454.0";
$acct_id_ml_3 = "3171";
$pool_size_ml_3 = "1454.0";
$entry1_pool_ml_3 = "953.0";
$entry1_odds_ml_3p = "0.525708289612";
$entry2_pool_ml_3 = "501.0";
$entry2_odds_ml_3p = "1.90219560878";
$max_odds_ml_3 = "1.90219560878";
$entry1_odds_ml_3 = convertOdds($entry1_odds_ml_3p, $odds_type, $max_odds_ml_3);
$entry2_odds_ml_3 = convertOdds($entry2_odds_ml_3p, $odds_type, 0);
$pool_id_pwp_3 = "126";
$point_spread1_pwp_3 = "-7.0";
$point_spread2_pwp_3 = "+7.0";
$point_spread3_pwp_3 = "+7.0,Green_Bay_Packers";
$total_pool_pwp_3 = "705.0";
$acct_id_pwp_3 = "3172";
$pool_size_pwp_3 = "705.0";
$entry1_pool_pwp_3 = "3.0";
$entry1_odds_pwp_3p = "234.0";
$entry2_pool_pwp_3 = "700.0";
$entry2_odds_pwp_3p = "0.00714285714286";
$entry3_pool_pwp_3 = "2.0";
$entry3_odds_pwp_3p = "351.5";
$max_odds_pwp_3 = "351.5";
$entry1_odds_pwp_3 = convertOdds($entry1_odds_pwp_3p, $odds_type, $max_odds_pwp_3);
$entry2_odds_pwp_3 = convertOdds($entry2_odds_pwp_3p, $odds_type, $max_odds_pwp_3);
$entry3_odds_pwp_3 = convertOdds($entry3_odds_pwp_3p, $odds_type, 0);
$pool_id_ou_3 = "127";
$point_spread1_ou_3 = "+47.5";
$point_spread2_ou_3 = "+47.5";
$point_spread_ou_3 = "47.5";
$total_pool_ou_3 = "19.0";
$acct_id_ou_3 = "3173";
$pool_size_ou_3 = "19.0";
$entry1_pool_ou_3 = "14.0";
$entry1_odds_ou_3p = "0.357142857143";
$entry2_pool_ou_3 = "5.0";
$entry2_odds_ou_3p = "2.8";
$max_odds_ou_3 = "2.8";
$entry1_odds_ou_3 = convertOdds($entry1_odds_ou_3p, $odds_type, $max_odds_ou_3);
$entry2_odds_ou_3 = convertOdds($entry2_odds_ou_3p, $odds_type, 0);
$compareName_3 = "Bovada";
$point_spread1_sp_3_cmp = "pk";
$entry1_odds_sp_3_cmpp = "None";
$entry1_odds_sp_3_cmp = convertOdds($entry1_odds_sp_3_cmpp, 3 + $odds_type, 0);
$overlay1_sp_3 = "0.0%";
$point_spread2_sp_3_cmp = "pk";
$entry2_odds_sp_3_cmpp = "None";
$entry2_odds_sp_3_cmp = convertOdds($entry2_odds_sp_3_cmpp, 3 + $odds_type, 0);
$overlay2_sp_3 = "0.0%";
$point_spread1_ml_3_cmp = "pk";
$entry1_odds_ml_3_cmpp = "None";
$entry1_odds_ml_3_cmp = convertOdds($entry1_odds_ml_3_cmpp, 3 + $odds_type, 0);
$overlay1_ml_3 = "0.0%";
$point_spread2_ml_3_cmp = "pk";
$entry2_odds_ml_3_cmpp = "None";
$entry2_odds_ml_3_cmp = convertOdds($entry2_odds_ml_3_cmpp, 3 + $odds_type, 0);
$overlay2_ml_3 = "0.0%";
$point_spread1_pwp_3_cmp = "pk";
$entry1_odds_pwp_3_cmpp = "None";
$entry1_odds_pwp_3_cmp = convertOdds($entry1_odds_pwp_3_cmpp, 3 + $odds_type, 0);
$overlay1_pwp_3 = "0.0%";
$point_spread2_pwp_3_cmp = "pk";
$entry2_odds_pwp_3_cmpp = "None";
$entry2_odds_pwp_3_cmp = convertOdds($entry2_odds_pwp_3_cmpp, 3 + $odds_type, 0);
$overlay2_pwp_3 = "0.0%";
$point_spread3_pwp_3_cmp = "pk";
$entry3_odds_pwp_3_cmpp = "0.0";
$entry3_odds_pwp_3_cmp = convertOdds($entry3_odds_pwp_3_cmpp, 3 + $odds_type, 0);
$overlay3_pwp_3 = "0.0%";
$point_spread1_ou_3_cmp = "pk";
$entry1_odds_ou_3_cmpp = "None";
$entry1_odds_ou_3_cmp = convertOdds($entry1_odds_ou_3_cmpp, 3 + $odds_type, 0);
$overlay1_ou_3 = "0.0%";
$point_spread2_ou_3_cmp = "pk";
$entry2_odds_ou_3_cmpp = "None";
$entry2_odds_ou_3_cmp = convertOdds($entry2_odds_ou_3_cmpp, 3 + $odds_type, 0);
$overlay2_ou_3 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_3" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'><input type='hidden' name='gamename_arr[]' value=" . "$gamename_3_p" . " /><input type='hidden' name='gamename2_arr[]' value=" . "$gamename2_3_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='entry1_name_arr[]' value=" . "$entry1_name_3_p" . " /><input type='hidden' name='entry2_name_arr[]' value=" . "$entry2_name_3_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='gamedate_arr[]' value=" . "$gamedate" . " /></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_sp_3" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_sp_3" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ml_3" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ml_3" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_pwp_3" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_pwp_3" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ou_3" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ou_3" . " />\n";
echo "<td>" . "$entry1_rot_3" . "<input type='hidden' name='game_desc_id_arr[]' id='game_desc_id' value=" . "$game_desc_id_3" . " /><input type='hidden' name='rot_id_e1_game3' id='rot_id_e1_game3' value=" . "$entry1_rot_3" . " /><input type='hidden' name='rot_id_e2_game3' id='rot_id_e2_game3' value=" . "$entry2_rot_3" . " /><input type='hidden' name='rot_id_e3_game3' id='rot_id_e3_game3' value=" . "$entry3_rot_3" . " /></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_3" . "<input type='hidden' name='game_num_arr[]' value='3'" . " /><input type='hidden' name='acct_id_sp[]' value=" . "$acct_id_sp_3" . " /><input type='hidden' name='acct_id_pwp[]' value=" . "$acct_id_pwp_3" . " /><input type='hidden' name='acct_id_ml[]' value=" . "$acct_id_ml_3" . " /><input type='hidden' name='acct_id_ou[]' value=" . "$acct_id_ou_3" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_3" . " " . "$entry1_odds_sp_3" . "</label><input type='checkbox' name='spread_game3[]' id='cb_sp_e1_g3' value=" . "$entry1_rot_3" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_3" . " " . "$entry1_odds_pwp_3" . "</label><input type='checkbox' name='pwp_game3[]' id='cb_pwp_e1_g3' value=" . "$entry1_rot_3" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_3" . "</label><input type='checkbox' name='ml_game3[]' id='cb_ml_e1_g3' value=" . "$entry1_rot_3" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_3" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_3" . "</label><input type='checkbox' name='overunder_game3[]' id='cb_ou_e1_g3' value=" . "$entry1_rot_3_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_3" . "</label><input type='checkbox' name='overunder_game3[]' id='cb_ou_e2_g3' value=" . "$entry2_rot_3_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game3' id='betbox_e1_game3' type='text' onclick='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_3" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_3" . " " . "$entry2_odds_sp_3" . "</label><input type='checkbox' name='spread_game3[]' id='cb_sp_e2_g3' value=" . "$entry2_rot_3" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_3" . " " . "$entry2_odds_pwp_3" . "</label><input type='checkbox' name='pwp_game3[]' id='cb_pwp_e2_g3' value=" . "$entry2_rot_3" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_3" . "</label><input type='checkbox' name='ml_game3[]' id='cb_ml_e2_g3' value=" . "$entry2_rot_3" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game3' id='betbox_e2_game3' type='text' onclick='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td><input type='hidden' name='point_spread1_sp_3' value= " . "$point_spread1_sp_3" . " /><input type='hidden' name='point_spread2_sp_3' value= " . "$point_spread2_sp_3" . " /><input type='hidden' name='point_spread1_pwp_3' value= " . "$point_spread1_pwp_3" . " /><input type='hidden' name='point_spread2_pwp_3' value= " . "$point_spread2_pwp_3" . " /><input type='hidden' name='point_spread3_pwp_3' value= " . "$point_spread3_pwp_3" . " /><input type='hidden' name='point_spread1_ou_3' value= " . "$point_spread1_ou_3" . " /><input type='hidden' name='point_spread2_ou_3' value= " . "$point_spread2_ou_3" . " /></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_3" . "</label><input type='checkbox' name='pwp_game3[]' id='cb_pwp_e3_g3' value=" . "$entry3_rot_3" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game3' id='betbox_e3_game3' type='text' onclick='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<input type='hidden' name='entry1_odds_sp_arr[]' value=" . "$entry1_odds_sp_3p" . " /><input type='hidden' name='entry2_odds_sp_arr[]' value=" . "$entry2_odds_sp_3p" . " />\n";
echo "<input type='hidden' name='entry1_odds_pwp_arr[]' value=" . "$entry1_odds_pwp_3p" . " /><input type='hidden' name='entry2_odds_pwp_arr[]' value=" . "$entry2_odds_pwp_3p" . " /><input type='hidden' name='entry3_odds_pwp_arr[]' value=" . "$entry3_odds_pwp_3p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ml_arr[]' value=" . "$entry1_odds_ml_3p" . " /><input type='hidden' name='entry2_odds_ml_arr[]' value=" . "$entry2_odds_ml_3p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ou_arr[]' value=" . "$entry1_odds_ou_3p" . " /><input type='hidden' name='entry2_odds_ou_arr[]' value=" . "$entry2_odds_ou_3p" . " />\n";
echo "<input type='hidden' name='pool_size_sp_game3' id='pool_size_sp_game3' value=" . "$pool_size_sp_3" . " />\n";
echo "<input type='hidden' name='pool_size_pwp_game3' id='pool_size_pwp_game3' value=" . "$pool_size_pwp_3" . " />\n";
echo "<input type='hidden' name='pool_size_ml_game3' id='pool_size_ml_game3' value=" . "$pool_size_ml_3" . " />\n";
echo "<input type='hidden' name='pool_size_ou_game3' id='pool_size_ou_game3' value=" . "$pool_size_ou_3" . " />\n";
echo "<input type='hidden' name='rot_id_e1_game3_ou' id='rot_id_e1_game3_ou' value=" . "$entry1_rot_3_ou" . " /><input type='hidden' name='rot_id_e2_game3_ou' id='rot_id_e2_game3_ou' value=" . "$entry2_rot_3_ou" . " />\n";
echo "<input type='hidden' name='gamedate2_arr[]' value=" . "$gamedate2_3" . " />\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_3" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_3" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_3_cmp" . " " . "$entry1_odds_sp_3_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_3_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_3_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_3" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_3_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_3_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_3" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_3" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_3_cmp" . " " . "$entry2_odds_sp_3_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_3_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_3" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_3_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_3" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_3" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_4 = "1:00 PM EDT, MetLife Stadium, East Rutherford";
$gamename_4_p = str_replace(" ", "_", "1:00 PM EDT, MetLife Stadium, East Rutherford");
$gameNum = "4";
$game_desc_id_4 = "42";
$total_games++;
$entry1_rot_4 = "107";
$entry1_name_4 = "Cleveland Browns";
$entry1_name_4_p = str_replace(" ", "_", "Cleveland Browns");
$entry2_rot_4 = "108";
$entry2_name_4 = "New York Giants";
$entry2_name_4_p = str_replace(" ", "_", "New York Giants");
$entry3_rot_4 = "3";
$entry1_rot_4_ou = "1";
$entry2_rot_4_ou = "2";
$gamename2_4 = "Cleveland Browns at New York Giants";
$gamename2_4_p = str_replace(" ", "_", "Cleveland Browns at New York Giants");
$gamedate2_4 = "07_Oct_2012";
$num_entries_4 = "2";
$pool_id_sp_4 = "128";
$point_spread1_sp_4 = "+9.0";
$point_spread2_sp_4 = "-9.0";
$total_pool_sp_4 = "2902.0";
$acct_id_sp_4 = "3174";
$pool_size_sp_4 = "2902.0";
$entry1_pool_sp_4 = "1302.0";
$entry1_odds_sp_4p = "1.22887864823";
$entry2_pool_sp_4 = "1600.0";
$entry2_odds_sp_4p = "0.81375";
$max_odds_sp_4 = "1.22887864823";
$entry1_odds_sp_4 = convertOdds($entry1_odds_sp_4p, $odds_type, 0);
$entry2_odds_sp_4 = convertOdds($entry2_odds_sp_4p, $odds_type, $max_odds_sp_4);
$pool_id_ml_4 = "129";
$point_spread1_ml_4 = "pk";
$point_spread2_ml_4 = "pk";
$total_pool_ml_4 = "0.0";
$acct_id_ml_4 = "3175";
$pool_size_ml_4 = "0.0";
$entry1_pool_ml_4 = "0.0";
$entry1_odds_ml_4p = "0.01";
$entry2_pool_ml_4 = "0.0";
$entry2_odds_ml_4p = "0.01";
$max_odds_ml_4 = "0.01";
$entry1_odds_ml_4 = convertOdds($entry1_odds_ml_4p, $odds_type, 0);
$entry2_odds_ml_4 = convertOdds($entry2_odds_ml_4p, $odds_type, $max_odds_ml_4);
$pool_id_pwp_4 = "130";
$point_spread1_pwp_4 = "+9.0";
$point_spread2_pwp_4 = "-9.0";
$point_spread3_pwp_4 = "+9.0,Cleveland_Browns";
$total_pool_pwp_4 = "902.0";
$acct_id_pwp_4 = "3176";
$pool_size_pwp_4 = "902.0";
$entry1_pool_pwp_4 = "0.0";
$entry1_odds_pwp_4p = "902.0";
$entry2_pool_pwp_4 = "902.0";
$entry2_odds_pwp_4p = "0.0";
$entry3_pool_pwp_4 = "0.0";
$entry3_odds_pwp_4p = "902.0";
$max_odds_pwp_4 = "902.0";
$entry1_odds_pwp_4 = convertOdds($entry1_odds_pwp_4p, $odds_type, 0);
$entry2_odds_pwp_4 = convertOdds($entry2_odds_pwp_4p, $odds_type, $max_odds_pwp_4);
$entry3_odds_pwp_4 = convertOdds($entry3_odds_pwp_4p, $odds_type, $max_odds_pwp_4);
$pool_id_ou_4 = "131";
$point_spread1_ou_4 = "+44.0";
$point_spread2_ou_4 = "+44.0";
$point_spread_ou_4 = "44.0";
$total_pool_ou_4 = "2310.0";
$acct_id_ou_4 = "3177";
$pool_size_ou_4 = "2310.0";
$entry1_pool_ou_4 = "1002.0";
$entry1_odds_ou_4p = "1.30538922156";
$entry2_pool_ou_4 = "1308.0";
$entry2_odds_ou_4p = "0.766055045872";
$max_odds_ou_4 = "1.30538922156";
$entry1_odds_ou_4 = convertOdds($entry1_odds_ou_4p, $odds_type, 0);
$entry2_odds_ou_4 = convertOdds($entry2_odds_ou_4p, $odds_type, $max_odds_ou_4);
$compareName_4 = "Bovada";
$point_spread1_sp_4_cmp = "pk";
$entry1_odds_sp_4_cmpp = "None";
$entry1_odds_sp_4_cmp = convertOdds($entry1_odds_sp_4_cmpp, 3 + $odds_type, 0);
$overlay1_sp_4 = "0.0%";
$point_spread2_sp_4_cmp = "pk";
$entry2_odds_sp_4_cmpp = "None";
$entry2_odds_sp_4_cmp = convertOdds($entry2_odds_sp_4_cmpp, 3 + $odds_type, 0);
$overlay2_sp_4 = "0.0%";
$point_spread1_ml_4_cmp = "pk";
$entry1_odds_ml_4_cmpp = "None";
$entry1_odds_ml_4_cmp = convertOdds($entry1_odds_ml_4_cmpp, 3 + $odds_type, 0);
$overlay1_ml_4 = "0.0%";
$point_spread2_ml_4_cmp = "pk";
$entry2_odds_ml_4_cmpp = "None";
$entry2_odds_ml_4_cmp = convertOdds($entry2_odds_ml_4_cmpp, 3 + $odds_type, 0);
$overlay2_ml_4 = "0.0%";
$point_spread1_pwp_4_cmp = "pk";
$entry1_odds_pwp_4_cmpp = "None";
$entry1_odds_pwp_4_cmp = convertOdds($entry1_odds_pwp_4_cmpp, 3 + $odds_type, 0);
$overlay1_pwp_4 = "0.0%";
$point_spread2_pwp_4_cmp = "pk";
$entry2_odds_pwp_4_cmpp = "None";
$entry2_odds_pwp_4_cmp = convertOdds($entry2_odds_pwp_4_cmpp, 3 + $odds_type, 0);
$overlay2_pwp_4 = "0.0%";
$point_spread3_pwp_4_cmp = "pk";
$entry3_odds_pwp_4_cmpp = "0.0";
$entry3_odds_pwp_4_cmp = convertOdds($entry3_odds_pwp_4_cmpp, 3 + $odds_type, 0);
$overlay3_pwp_4 = "0.0%";
$point_spread1_ou_4_cmp = "pk";
$entry1_odds_ou_4_cmpp = "None";
$entry1_odds_ou_4_cmp = convertOdds($entry1_odds_ou_4_cmpp, 3 + $odds_type, 0);
$overlay1_ou_4 = "0.0%";
$point_spread2_ou_4_cmp = "pk";
$entry2_odds_ou_4_cmpp = "None";
$entry2_odds_ou_4_cmp = convertOdds($entry2_odds_ou_4_cmpp, 3 + $odds_type, 0);
$overlay2_ou_4 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_4" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'><input type='hidden' name='gamename_arr[]' value=" . "$gamename_4_p" . " /><input type='hidden' name='gamename2_arr[]' value=" . "$gamename2_4_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='entry1_name_arr[]' value=" . "$entry1_name_4_p" . " /><input type='hidden' name='entry2_name_arr[]' value=" . "$entry2_name_4_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='gamedate_arr[]' value=" . "$gamedate" . " /></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_sp_4" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_sp_4" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ml_4" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ml_4" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_pwp_4" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_pwp_4" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ou_4" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ou_4" . " />\n";
echo "<td>" . "$entry1_rot_4" . "<input type='hidden' name='game_desc_id_arr[]' id='game_desc_id' value=" . "$game_desc_id_4" . " /><input type='hidden' name='rot_id_e1_game4' id='rot_id_e1_game4' value=" . "$entry1_rot_4" . " /><input type='hidden' name='rot_id_e2_game4' id='rot_id_e2_game4' value=" . "$entry2_rot_4" . " /><input type='hidden' name='rot_id_e3_game4' id='rot_id_e3_game4' value=" . "$entry3_rot_4" . " /></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_4" . "<input type='hidden' name='game_num_arr[]' value='4'" . " /><input type='hidden' name='acct_id_sp[]' value=" . "$acct_id_sp_4" . " /><input type='hidden' name='acct_id_pwp[]' value=" . "$acct_id_pwp_4" . " /><input type='hidden' name='acct_id_ml[]' value=" . "$acct_id_ml_4" . " /><input type='hidden' name='acct_id_ou[]' value=" . "$acct_id_ou_4" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_4" . " " . "$entry1_odds_sp_4" . "</label><input type='checkbox' name='spread_game4[]' id='cb_sp_e1_g4' value=" . "$entry1_rot_4" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_4" . " " . "$entry1_odds_pwp_4" . "</label><input type='checkbox' name='pwp_game4[]' id='cb_pwp_e1_g4' value=" . "$entry1_rot_4" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_4" . "</label><input type='checkbox' name='ml_game4[]' id='cb_ml_e1_g4' value=" . "$entry1_rot_4" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_4" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_4" . "</label><input type='checkbox' name='overunder_game4[]' id='cb_ou_e1_g4' value=" . "$entry1_rot_4_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_4" . "</label><input type='checkbox' name='overunder_game4[]' id='cb_ou_e2_g4' value=" . "$entry2_rot_4_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game4' id='betbox_e1_game4' type='text' onclick='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_4" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_4" . " " . "$entry2_odds_sp_4" . "</label><input type='checkbox' name='spread_game4[]' id='cb_sp_e2_g4' value=" . "$entry2_rot_4" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_4" . " " . "$entry2_odds_pwp_4" . "</label><input type='checkbox' name='pwp_game4[]' id='cb_pwp_e2_g4' value=" . "$entry2_rot_4" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_4" . "</label><input type='checkbox' name='ml_game4[]' id='cb_ml_e2_g4' value=" . "$entry2_rot_4" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game4' id='betbox_e2_game4' type='text' onclick='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td><input type='hidden' name='point_spread1_sp_4' value= " . "$point_spread1_sp_4" . " /><input type='hidden' name='point_spread2_sp_4' value= " . "$point_spread2_sp_4" . " /><input type='hidden' name='point_spread1_pwp_4' value= " . "$point_spread1_pwp_4" . " /><input type='hidden' name='point_spread2_pwp_4' value= " . "$point_spread2_pwp_4" . " /><input type='hidden' name='point_spread3_pwp_4' value= " . "$point_spread3_pwp_4" . " /><input type='hidden' name='point_spread1_ou_4' value= " . "$point_spread1_ou_4" . " /><input type='hidden' name='point_spread2_ou_4' value= " . "$point_spread2_ou_4" . " /></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_4" . "</label><input type='checkbox' name='pwp_game4[]' id='cb_pwp_e3_g4' value=" . "$entry3_rot_4" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game4' id='betbox_e3_game4' type='text' onclick='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<input type='hidden' name='entry1_odds_sp_arr[]' value=" . "$entry1_odds_sp_4p" . " /><input type='hidden' name='entry2_odds_sp_arr[]' value=" . "$entry2_odds_sp_4p" . " />\n";
echo "<input type='hidden' name='entry1_odds_pwp_arr[]' value=" . "$entry1_odds_pwp_4p" . " /><input type='hidden' name='entry2_odds_pwp_arr[]' value=" . "$entry2_odds_pwp_4p" . " /><input type='hidden' name='entry3_odds_pwp_arr[]' value=" . "$entry3_odds_pwp_4p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ml_arr[]' value=" . "$entry1_odds_ml_4p" . " /><input type='hidden' name='entry2_odds_ml_arr[]' value=" . "$entry2_odds_ml_4p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ou_arr[]' value=" . "$entry1_odds_ou_4p" . " /><input type='hidden' name='entry2_odds_ou_arr[]' value=" . "$entry2_odds_ou_4p" . " />\n";
echo "<input type='hidden' name='pool_size_sp_game4' id='pool_size_sp_game4' value=" . "$pool_size_sp_4" . " />\n";
echo "<input type='hidden' name='pool_size_pwp_game4' id='pool_size_pwp_game4' value=" . "$pool_size_pwp_4" . " />\n";
echo "<input type='hidden' name='pool_size_ml_game4' id='pool_size_ml_game4' value=" . "$pool_size_ml_4" . " />\n";
echo "<input type='hidden' name='pool_size_ou_game4' id='pool_size_ou_game4' value=" . "$pool_size_ou_4" . " />\n";
echo "<input type='hidden' name='rot_id_e1_game4_ou' id='rot_id_e1_game4_ou' value=" . "$entry1_rot_4_ou" . " /><input type='hidden' name='rot_id_e2_game4_ou' id='rot_id_e2_game4_ou' value=" . "$entry2_rot_4_ou" . " />\n";
echo "<input type='hidden' name='gamedate2_arr[]' value=" . "$gamedate2_4" . " />\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_4" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_4" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_4_cmp" . " " . "$entry1_odds_sp_4_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_4_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_4_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_4" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_4_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_4_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_4" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_4" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_4_cmp" . " " . "$entry2_odds_sp_4_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_4_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_4" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_4_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_4" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_4" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_5 = "1:00 PM EDT, Hubert H. Humphrey Metrodome, Minneapolis";
$gamename_5_p = str_replace(" ", "_", "1:00 PM EDT, Hubert H. Humphrey Metrodome, Minneapolis");
$gameNum = "5";
$game_desc_id_5 = "43";
$total_games++;
$entry1_rot_5 = "109";
$entry1_name_5 = "Tennessee Titans";
$entry1_name_5_p = str_replace(" ", "_", "Tennessee Titans");
$entry2_rot_5 = "110";
$entry2_name_5 = "Minnesota Vikings";
$entry2_name_5_p = str_replace(" ", "_", "Minnesota Vikings");
$entry3_rot_5 = "3";
$entry1_rot_5_ou = "1";
$entry2_rot_5_ou = "2";
$gamename2_5 = "Tennessee Titans at Minnesota Vikings";
$gamename2_5_p = str_replace(" ", "_", "Tennessee Titans at Minnesota Vikings");
$gamedate2_5 = "07_Oct_2012";
$num_entries_5 = "2";
$pool_id_sp_5 = "132";
$point_spread1_sp_5 = "+5.5";
$point_spread2_sp_5 = "-5.5";
$total_pool_sp_5 = "609.0";
$acct_id_sp_5 = "3178";
$pool_size_sp_5 = "609.0";
$entry1_pool_sp_5 = "609.0";
$entry1_odds_sp_5p = "0.0";
$entry2_pool_sp_5 = "0.0";
$entry2_odds_sp_5p = "609.0";
$max_odds_sp_5 = "609.0";
$entry1_odds_sp_5 = convertOdds($entry1_odds_sp_5p, $odds_type, $max_odds_sp_5);
$entry2_odds_sp_5 = convertOdds($entry2_odds_sp_5p, $odds_type, 0);
$pool_id_ml_5 = "133";
$point_spread1_ml_5 = "pk";
$point_spread2_ml_5 = "pk";
$total_pool_ml_5 = "2700.0";
$acct_id_ml_5 = "3179";
$pool_size_ml_5 = "2700.0";
$entry1_pool_ml_5 = "1700.0";
$entry1_odds_ml_5p = "0.588235294118";
$entry2_pool_ml_5 = "1000.0";
$entry2_odds_ml_5p = "1.7";
$max_odds_ml_5 = "1.7";
$entry1_odds_ml_5 = convertOdds($entry1_odds_ml_5p, $odds_type, $max_odds_ml_5);
$entry2_odds_ml_5 = convertOdds($entry2_odds_ml_5p, $odds_type, 0);
$pool_id_pwp_5 = "134";
$point_spread1_pwp_5 = "+6.0";
$point_spread2_pwp_5 = "-6.0";
$point_spread3_pwp_5 = "+6.0,Tennessee_Titans";
$total_pool_pwp_5 = "1000.0";
$acct_id_pwp_5 = "3180";
$pool_size_pwp_5 = "1000.0";
$entry1_pool_pwp_5 = "0.0";
$entry1_odds_pwp_5p = "1000.0";
$entry2_pool_pwp_5 = "0.0";
$entry2_odds_pwp_5p = "1000.0";
$entry3_pool_pwp_5 = "1000.0";
$entry3_odds_pwp_5p = "0.0";
$max_odds_pwp_5 = "1000.0";
$entry1_odds_pwp_5 = convertOdds($entry1_odds_pwp_5p, $odds_type, 0);
$entry2_odds_pwp_5 = convertOdds($entry2_odds_pwp_5p, $odds_type, $max_odds_pwp_5);
$entry3_odds_pwp_5 = convertOdds($entry3_odds_pwp_5p, $odds_type, $max_odds_pwp_5);
$pool_id_ou_5 = "135";
$point_spread1_ou_5 = "+43.5";
$point_spread2_ou_5 = "+43.5";
$point_spread_ou_5 = "43.5";
$total_pool_ou_5 = "2403.0";
$acct_id_ou_5 = "3181";
$pool_size_ou_5 = "2403.0";
$entry1_pool_ou_5 = "1300.0";
$entry1_odds_ou_5p = "0.848461538462";
$entry2_pool_ou_5 = "1103.0";
$entry2_odds_ou_5p = "1.1786038078";
$max_odds_ou_5 = "1.1786038078";
$entry1_odds_ou_5 = convertOdds($entry1_odds_ou_5p, $odds_type, $max_odds_ou_5);
$entry2_odds_ou_5 = convertOdds($entry2_odds_ou_5p, $odds_type, 0);
$compareName_5 = "Bovada";
$point_spread1_sp_5_cmp = "pk";
$entry1_odds_sp_5_cmpp = "None";
$entry1_odds_sp_5_cmp = convertOdds($entry1_odds_sp_5_cmpp, 3 + $odds_type, 0);
$overlay1_sp_5 = "0.0%";
$point_spread2_sp_5_cmp = "pk";
$entry2_odds_sp_5_cmpp = "None";
$entry2_odds_sp_5_cmp = convertOdds($entry2_odds_sp_5_cmpp, 3 + $odds_type, 0);
$overlay2_sp_5 = "0.0%";
$point_spread1_ml_5_cmp = "pk";
$entry1_odds_ml_5_cmpp = "None";
$entry1_odds_ml_5_cmp = convertOdds($entry1_odds_ml_5_cmpp, 3 + $odds_type, 0);
$overlay1_ml_5 = "0.0%";
$point_spread2_ml_5_cmp = "pk";
$entry2_odds_ml_5_cmpp = "None";
$entry2_odds_ml_5_cmp = convertOdds($entry2_odds_ml_5_cmpp, 3 + $odds_type, 0);
$overlay2_ml_5 = "0.0%";
$point_spread1_pwp_5_cmp = "pk";
$entry1_odds_pwp_5_cmpp = "None";
$entry1_odds_pwp_5_cmp = convertOdds($entry1_odds_pwp_5_cmpp, 3 + $odds_type, 0);
$overlay1_pwp_5 = "0.0%";
$point_spread2_pwp_5_cmp = "pk";
$entry2_odds_pwp_5_cmpp = "None";
$entry2_odds_pwp_5_cmp = convertOdds($entry2_odds_pwp_5_cmpp, 3 + $odds_type, 0);
$overlay2_pwp_5 = "0.0%";
$point_spread3_pwp_5_cmp = "pk";
$entry3_odds_pwp_5_cmpp = "0.0";
$entry3_odds_pwp_5_cmp = convertOdds($entry3_odds_pwp_5_cmpp, 3 + $odds_type, 0);
$overlay3_pwp_5 = "0.0%";
$point_spread1_ou_5_cmp = "pk";
$entry1_odds_ou_5_cmpp = "None";
$entry1_odds_ou_5_cmp = convertOdds($entry1_odds_ou_5_cmpp, 3 + $odds_type, 0);
$overlay1_ou_5 = "0.0%";
$point_spread2_ou_5_cmp = "pk";
$entry2_odds_ou_5_cmpp = "None";
$entry2_odds_ou_5_cmp = convertOdds($entry2_odds_ou_5_cmpp, 3 + $odds_type, 0);
$overlay2_ou_5 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_5" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'><input type='hidden' name='gamename_arr[]' value=" . "$gamename_5_p" . " /><input type='hidden' name='gamename2_arr[]' value=" . "$gamename2_5_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='entry1_name_arr[]' value=" . "$entry1_name_5_p" . " /><input type='hidden' name='entry2_name_arr[]' value=" . "$entry2_name_5_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='gamedate_arr[]' value=" . "$gamedate" . " /></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_sp_5" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_sp_5" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ml_5" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ml_5" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_pwp_5" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_pwp_5" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ou_5" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ou_5" . " />\n";
echo "<td>" . "$entry1_rot_5" . "<input type='hidden' name='game_desc_id_arr[]' id='game_desc_id' value=" . "$game_desc_id_5" . " /><input type='hidden' name='rot_id_e1_game5' id='rot_id_e1_game5' value=" . "$entry1_rot_5" . " /><input type='hidden' name='rot_id_e2_game5' id='rot_id_e2_game5' value=" . "$entry2_rot_5" . " /><input type='hidden' name='rot_id_e3_game5' id='rot_id_e3_game5' value=" . "$entry3_rot_5" . " /></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_5" . "<input type='hidden' name='game_num_arr[]' value='5'" . " /><input type='hidden' name='acct_id_sp[]' value=" . "$acct_id_sp_5" . " /><input type='hidden' name='acct_id_pwp[]' value=" . "$acct_id_pwp_5" . " /><input type='hidden' name='acct_id_ml[]' value=" . "$acct_id_ml_5" . " /><input type='hidden' name='acct_id_ou[]' value=" . "$acct_id_ou_5" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_5" . " " . "$entry1_odds_sp_5" . "</label><input type='checkbox' name='spread_game5[]' id='cb_sp_e1_g5' value=" . "$entry1_rot_5" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_5" . " " . "$entry1_odds_pwp_5" . "</label><input type='checkbox' name='pwp_game5[]' id='cb_pwp_e1_g5' value=" . "$entry1_rot_5" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_5" . "</label><input type='checkbox' name='ml_game5[]' id='cb_ml_e1_g5' value=" . "$entry1_rot_5" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_5" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_5" . "</label><input type='checkbox' name='overunder_game5[]' id='cb_ou_e1_g5' value=" . "$entry1_rot_5_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_5" . "</label><input type='checkbox' name='overunder_game5[]' id='cb_ou_e2_g5' value=" . "$entry2_rot_5_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game5' id='betbox_e1_game5' type='text' onclick='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_5" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_5" . " " . "$entry2_odds_sp_5" . "</label><input type='checkbox' name='spread_game5[]' id='cb_sp_e2_g5' value=" . "$entry2_rot_5" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_5" . " " . "$entry2_odds_pwp_5" . "</label><input type='checkbox' name='pwp_game5[]' id='cb_pwp_e2_g5' value=" . "$entry2_rot_5" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_5" . "</label><input type='checkbox' name='ml_game5[]' id='cb_ml_e2_g5' value=" . "$entry2_rot_5" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game5' id='betbox_e2_game5' type='text' onclick='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td><input type='hidden' name='point_spread1_sp_5' value= " . "$point_spread1_sp_5" . " /><input type='hidden' name='point_spread2_sp_5' value= " . "$point_spread2_sp_5" . " /><input type='hidden' name='point_spread1_pwp_5' value= " . "$point_spread1_pwp_5" . " /><input type='hidden' name='point_spread2_pwp_5' value= " . "$point_spread2_pwp_5" . " /><input type='hidden' name='point_spread3_pwp_5' value= " . "$point_spread3_pwp_5" . " /><input type='hidden' name='point_spread1_ou_5' value= " . "$point_spread1_ou_5" . " /><input type='hidden' name='point_spread2_ou_5' value= " . "$point_spread2_ou_5" . " /></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_5" . "</label><input type='checkbox' name='pwp_game5[]' id='cb_pwp_e3_g5' value=" . "$entry3_rot_5" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game5' id='betbox_e3_game5' type='text' onclick='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<input type='hidden' name='entry1_odds_sp_arr[]' value=" . "$entry1_odds_sp_5p" . " /><input type='hidden' name='entry2_odds_sp_arr[]' value=" . "$entry2_odds_sp_5p" . " />\n";
echo "<input type='hidden' name='entry1_odds_pwp_arr[]' value=" . "$entry1_odds_pwp_5p" . " /><input type='hidden' name='entry2_odds_pwp_arr[]' value=" . "$entry2_odds_pwp_5p" . " /><input type='hidden' name='entry3_odds_pwp_arr[]' value=" . "$entry3_odds_pwp_5p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ml_arr[]' value=" . "$entry1_odds_ml_5p" . " /><input type='hidden' name='entry2_odds_ml_arr[]' value=" . "$entry2_odds_ml_5p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ou_arr[]' value=" . "$entry1_odds_ou_5p" . " /><input type='hidden' name='entry2_odds_ou_arr[]' value=" . "$entry2_odds_ou_5p" . " />\n";
echo "<input type='hidden' name='pool_size_sp_game5' id='pool_size_sp_game5' value=" . "$pool_size_sp_5" . " />\n";
echo "<input type='hidden' name='pool_size_pwp_game5' id='pool_size_pwp_game5' value=" . "$pool_size_pwp_5" . " />\n";
echo "<input type='hidden' name='pool_size_ml_game5' id='pool_size_ml_game5' value=" . "$pool_size_ml_5" . " />\n";
echo "<input type='hidden' name='pool_size_ou_game5' id='pool_size_ou_game5' value=" . "$pool_size_ou_5" . " />\n";
echo "<input type='hidden' name='rot_id_e1_game5_ou' id='rot_id_e1_game5_ou' value=" . "$entry1_rot_5_ou" . " /><input type='hidden' name='rot_id_e2_game5_ou' id='rot_id_e2_game5_ou' value=" . "$entry2_rot_5_ou" . " />\n";
echo "<input type='hidden' name='gamedate2_arr[]' value=" . "$gamedate2_5" . " />\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_5" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_5" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_5_cmp" . " " . "$entry1_odds_sp_5_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_5_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_5_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_5" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_5_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_5_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_5" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_5" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_5_cmp" . " " . "$entry2_odds_sp_5_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_5_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_5" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_5_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_5" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_5" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</div>\n";
echo "<hr />\n";
$gamename_6 = "1:00 PM EDT, Paul Brown Stadium, Cincinnati";
$gamename_6_p = str_replace(" ", "_", "1:00 PM EDT, Paul Brown Stadium, Cincinnati");
$gameNum = "6";
$game_desc_id_6 = "44";
$total_games++;
$entry1_rot_6 = "111";
$entry1_name_6 = "Miami Dolphins";
$entry1_name_6_p = str_replace(" ", "_", "Miami Dolphins");
$entry2_rot_6 = "112";
$entry2_name_6 = "Cincinnati Bengals";
$entry2_name_6_p = str_replace(" ", "_", "Cincinnati Bengals");
$entry3_rot_6 = "3";
$entry1_rot_6_ou = "1";
$entry2_rot_6_ou = "2";
$gamename2_6 = "Miami Dolphins at Cincinnati Bengals";
$gamename2_6_p = str_replace(" ", "_", "Miami Dolphins at Cincinnati Bengals");
$gamedate2_6 = "07_Oct_2012";
$num_entries_6 = "2";
$pool_id_sp_6 = "136";
$point_spread1_sp_6 = "+3.5";
$point_spread2_sp_6 = "-3.5";
$total_pool_sp_6 = "911.0";
$acct_id_sp_6 = "3182";
$pool_size_sp_6 = "911.0";
$entry1_pool_sp_6 = "911.0";
$entry1_odds_sp_6p = "0.0";
$entry2_pool_sp_6 = "0.0";
$entry2_odds_sp_6p = "911.0";
$max_odds_sp_6 = "911.0";
$entry1_odds_sp_6 = convertOdds($entry1_odds_sp_6p, $odds_type, $max_odds_sp_6);
$entry2_odds_sp_6 = convertOdds($entry2_odds_sp_6p, $odds_type, 0);
$pool_id_ml_6 = "137";
$point_spread1_ml_6 = "pk";
$point_spread2_ml_6 = "pk";
$total_pool_ml_6 = "1145.0";
$acct_id_ml_6 = "3183";
$pool_size_ml_6 = "1145.0";
$entry1_pool_ml_6 = "704.0";
$entry1_odds_ml_6p = "0.626420454545";
$entry2_pool_ml_6 = "441.0";
$entry2_odds_ml_6p = "1.59637188209";
$max_odds_ml_6 = "1.59637188209";
$entry1_odds_ml_6 = convertOdds($entry1_odds_ml_6p, $odds_type, $max_odds_ml_6);
$entry2_odds_ml_6 = convertOdds($entry2_odds_ml_6p, $odds_type, 0);
$pool_id_pwp_6 = "138";
$point_spread1_pwp_6 = "+3.0";
$point_spread2_pwp_6 = "-3.0";
$point_spread3_pwp_6 = "+3.0,Miami_Dolphins";
$total_pool_pwp_6 = "700.0";
$acct_id_pwp_6 = "3184";
$pool_size_pwp_6 = "700.0";
$entry1_pool_pwp_6 = "0.0";
$entry1_odds_pwp_6p = "700.0";
$entry2_pool_pwp_6 = "700.0";
$entry2_odds_pwp_6p = "0.0";
$entry3_pool_pwp_6 = "0.0";
$entry3_odds_pwp_6p = "700.0";
$max_odds_pwp_6 = "700.0";
$entry1_odds_pwp_6 = convertOdds($entry1_odds_pwp_6p, $odds_type, 0);
$entry2_odds_pwp_6 = convertOdds($entry2_odds_pwp_6p, $odds_type, $max_odds_pwp_6);
$entry3_odds_pwp_6 = convertOdds($entry3_odds_pwp_6p, $odds_type, $max_odds_pwp_6);
$pool_id_ou_6 = "139";
$point_spread1_ou_6 = "+45.0";
$point_spread2_ou_6 = "+45.0";
$point_spread_ou_6 = "45.0";
$total_pool_ou_6 = "1200.0";
$acct_id_ou_6 = "3185";
$pool_size_ou_6 = "1200.0";
$entry1_pool_ou_6 = "1200.0";
$entry1_odds_ou_6p = "0.0";
$entry2_pool_ou_6 = "0.0";
$entry2_odds_ou_6p = "1200.0";
$max_odds_ou_6 = "1200.0";
$entry1_odds_ou_6 = convertOdds($entry1_odds_ou_6p, $odds_type, $max_odds_ou_6);
$entry2_odds_ou_6 = convertOdds($entry2_odds_ou_6p, $odds_type, 0);
$compareName_6 = "Bovada";
$point_spread1_sp_6_cmp = "pk";
$entry1_odds_sp_6_cmpp = "None";
$entry1_odds_sp_6_cmp = convertOdds($entry1_odds_sp_6_cmpp, 3 + $odds_type, 0);
$overlay1_sp_6 = "0.0%";
$point_spread2_sp_6_cmp = "pk";
$entry2_odds_sp_6_cmpp = "None";
$entry2_odds_sp_6_cmp = convertOdds($entry2_odds_sp_6_cmpp, 3 + $odds_type, 0);
$overlay2_sp_6 = "0.0%";
$point_spread1_ml_6_cmp = "pk";
$entry1_odds_ml_6_cmpp = "None";
$entry1_odds_ml_6_cmp = convertOdds($entry1_odds_ml_6_cmpp, 3 + $odds_type, 0);
$overlay1_ml_6 = "0.0%";
$point_spread2_ml_6_cmp = "pk";
$entry2_odds_ml_6_cmpp = "None";
$entry2_odds_ml_6_cmp = convertOdds($entry2_odds_ml_6_cmpp, 3 + $odds_type, 0);
$overlay2_ml_6 = "0.0%";
$point_spread1_pwp_6_cmp = "pk";
$entry1_odds_pwp_6_cmpp = "None";
$entry1_odds_pwp_6_cmp = convertOdds($entry1_odds_pwp_6_cmpp, 3 + $odds_type, 0);
$overlay1_pwp_6 = "0.0%";
$point_spread2_pwp_6_cmp = "pk";
$entry2_odds_pwp_6_cmpp = "None";
$entry2_odds_pwp_6_cmp = convertOdds($entry2_odds_pwp_6_cmpp, 3 + $odds_type, 0);
$overlay2_pwp_6 = "0.0%";
$point_spread3_pwp_6_cmp = "pk";
$entry3_odds_pwp_6_cmpp = "0.0";
$entry3_odds_pwp_6_cmp = convertOdds($entry3_odds_pwp_6_cmpp, 3 + $odds_type, 0);
$overlay3_pwp_6 = "0.0%";
$point_spread1_ou_6_cmp = "pk";
$entry1_odds_ou_6_cmpp = "None";
$entry1_odds_ou_6_cmp = convertOdds($entry1_odds_ou_6_cmpp, 3 + $odds_type, 0);
$overlay1_ou_6 = "0.0%";
$point_spread2_ou_6_cmp = "pk";
$entry2_odds_ou_6_cmpp = "None";
$entry2_odds_ou_6_cmp = convertOdds($entry2_odds_ou_6_cmpp, 3 + $odds_type, 0);
$overlay2_ou_6 = "0.0%";
echo "<div id='pool_view'>\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th colspan='3'; id='gameName'>" . "$gamename_6" . "</th>\n";
echo "<th colspan=" . "$colspan_header" . "; id='gameDate'><strong>Fireboil Current Odds</strong></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<th id='rot'></th>\n";
echo "<th id='teamName'><input type='hidden' name='gamename_arr[]' value=" . "$gamename_6_p" . " /><input type='hidden' name='gamename2_arr[]' value=" . "$gamename2_6_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='entry1_name_arr[]' value=" . "$entry1_name_6_p" . " /><input type='hidden' name='entry2_name_arr[]' value=" . "$entry2_name_6_p" . " /></th>\n";
echo "<th id='pointSpread'><input type='hidden' name='gamedate_arr[]' value=" . "$gamedate" . " /></th>\n";
echo "<th id='pointSpread'></th>\n";
echo "<th id='ouHeaderLeft'></th>\n";
echo "<th id='ouHeaderRight'></th>\n";
echo "<th id='betBoxHeader_nd'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_sp_6" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_sp_6" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ml_6" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ml_6" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_pwp_6" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_pwp_6" . " />\n";
echo "<input type='hidden' name='pool_id_arr[]' value=" . "$pool_id_ou_6" . " />\n";
echo "<input type='hidden' name='acct_id_arr[]' value=" . "$acct_id_ou_6" . " />\n";
echo "<td>" . "$entry1_rot_6" . "<input type='hidden' name='game_desc_id_arr[]' id='game_desc_id' value=" . "$game_desc_id_6" . " /><input type='hidden' name='rot_id_e1_game6' id='rot_id_e1_game6' value=" . "$entry1_rot_6" . " /><input type='hidden' name='rot_id_e2_game6' id='rot_id_e2_game6' value=" . "$entry2_rot_6" . " /><input type='hidden' name='rot_id_e3_game6' id='rot_id_e3_game6' value=" . "$entry3_rot_6" . " /></td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_6" . "<input type='hidden' name='game_num_arr[]' value='6'" . " /><input type='hidden' name='acct_id_sp[]' value=" . "$acct_id_sp_6" . " /><input type='hidden' name='acct_id_pwp[]' value=" . "$acct_id_pwp_6" . " /><input type='hidden' name='acct_id_ml[]' value=" . "$acct_id_ml_6" . " /><input type='hidden' name='acct_id_ou[]' value=" . "$acct_id_ou_6" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_6" . " " . "$entry1_odds_sp_6" . "</label><input type='checkbox' name='spread_game6[]' id='cb_sp_e1_g6' value=" . "$entry1_rot_6" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre7'>" . "$point_spread1_pwp_6" . " " . "$entry1_odds_pwp_6" . "</label><input type='checkbox' name='pwp_game6[]' id='cb_pwp_e1_g6' value=" . "$entry1_rot_6" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre'>" . "$entry1_odds_ml_6" . "</label><input type='checkbox' name='ml_game6[]' id='cb_ml_e1_g6' value=" . "$entry1_rot_6" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td rowspan='2'; id='overUnderNumber'>" . "$point_spread_ou_6" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_6" . "</label><input type='checkbox' name='overunder_game6[]' id='cb_ou_e1_g6' value=" . "$entry1_rot_6_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_6" . "</label><input type='checkbox' name='overunder_game6[]' id='cb_ou_e2_g6' value=" . "$entry2_rot_6_ou" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e1_game6' id='betbox_e1_game6' type='text' onclick='turnOffRealTime(myVar)' tabindex='14' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_6" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_6" . " " . "$entry2_odds_sp_6" . "</label><input type='checkbox' name='spread_game6[]' id='cb_sp_e2_g6' value=" . "$entry2_rot_6" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id='odds'><label class='bfd' for='genre8'>" . "$point_spread2_pwp_6" . " " . "$entry2_odds_pwp_6" . "</label><input type='checkbox' name='pwp_game6[]' id='cb_pwp_e2_g6' value=" . "$entry2_rot_6" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . "/></td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_6" . "</label><input type='checkbox' name='ml_game6[]' id='cb_ml_e2_g6' value=" . "$entry2_rot_6" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e2_game6' id='betbox_e2_game6' type='text' onclick='turnOffRealTime(myVar)' tabindex='15' /></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td></td>\n";
echo "<td><input type='hidden' name='point_spread1_sp_6' value= " . "$point_spread1_sp_6" . " /><input type='hidden' name='point_spread2_sp_6' value= " . "$point_spread2_sp_6" . " /><input type='hidden' name='point_spread1_pwp_6' value= " . "$point_spread1_pwp_6" . " /><input type='hidden' name='point_spread2_pwp_6' value= " . "$point_spread2_pwp_6" . " /><input type='hidden' name='point_spread3_pwp_6' value= " . "$point_spread3_pwp_6" . " /><input type='hidden' name='point_spread1_ou_6' value= " . "$point_spread1_ou_6" . " /><input type='hidden' name='point_spread2_ou_6' value= " . "$point_spread2_ou_6" . " /></td>\n";
echo "<td></td>\n";
echo "<td id='odds'><label class='bfd' for='genre9'>" . "Push" . " " . "$entry3_odds_pwp_6" . "</label><input type='checkbox' name='pwp_game6[]' id='cb_pwp_e3_g6' value=" . "$entry3_rot_6" . " onClick='turnOffRealTime(myVar)' " . "$bets_disabled" . " /></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td></td>\n";
echo "<td id=" . "$betheader_id" . "><input name='betbox_e3_game6' id='betbox_e3_game6' type='text' onclick='turnOffRealTime(myVar)' tabindex='16' /></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<input type='hidden' name='entry1_odds_sp_arr[]' value=" . "$entry1_odds_sp_6p" . " /><input type='hidden' name='entry2_odds_sp_arr[]' value=" . "$entry2_odds_sp_6p" . " />\n";
echo "<input type='hidden' name='entry1_odds_pwp_arr[]' value=" . "$entry1_odds_pwp_6p" . " /><input type='hidden' name='entry2_odds_pwp_arr[]' value=" . "$entry2_odds_pwp_6p" . " /><input type='hidden' name='entry3_odds_pwp_arr[]' value=" . "$entry3_odds_pwp_6p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ml_arr[]' value=" . "$entry1_odds_ml_6p" . " /><input type='hidden' name='entry2_odds_ml_arr[]' value=" . "$entry2_odds_ml_6p" . " />\n";
echo "<input type='hidden' name='entry1_odds_ou_arr[]' value=" . "$entry1_odds_ou_6p" . " /><input type='hidden' name='entry2_odds_ou_arr[]' value=" . "$entry2_odds_ou_6p" . " />\n";
echo "<input type='hidden' name='pool_size_sp_game6' id='pool_size_sp_game6' value=" . "$pool_size_sp_6" . " />\n";
echo "<input type='hidden' name='pool_size_pwp_game6' id='pool_size_pwp_game6' value=" . "$pool_size_pwp_6" . " />\n";
echo "<input type='hidden' name='pool_size_ml_game6' id='pool_size_ml_game6' value=" . "$pool_size_ml_6" . " />\n";
echo "<input type='hidden' name='pool_size_ou_game6' id='pool_size_ou_game6' value=" . "$pool_size_ou_6" . " />\n";
echo "<input type='hidden' name='rot_id_e1_game6_ou' id='rot_id_e1_game6_ou' value=" . "$entry1_rot_6_ou" . " /><input type='hidden' name='rot_id_e2_game6_ou' id='rot_id_e2_game6_ou' value=" . "$entry2_rot_6_ou" . " />\n";
echo "<input type='hidden' name='gamedate2_arr[]' value=" . "$gamedate2_6" . " />\n";
echo "<table class='tabley'>\n";
echo "<tr>\n";
echo "<th id='badRot'></th>\n";
echo "<th id='badTeamName'></th>\n";
echo "<th id='badPointSpread'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_pwp'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badPointSpread_ml'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "<th id='badOuHeaderRight'></th>\n";
echo "<th id='overlay_h2'></th>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td colspan='2'>Compare with current odds at: <strong>" . "$compareName_6" . "</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "<td></td>\n";
echo "<td id='overlay_data'><strong>Overlay</strong></td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry1_rot_6" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry1_name_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$point_spread1_sp_6_cmp" . " " . "$entry1_odds_sp_6_cmp" . "</label><input type='checkbox' name='genre2' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_sp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_pwp_6_cmp" . "</label><input type='checkbox' name='genre2' value='104odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_pwp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre2'>" . "$entry1_odds_ml_6_cmp" . "</label><input type='checkbox' name='genre2' value='101odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ml_6" . "</td>\n";
echo "<td rowspan='2'; id='overUnder'><label id='overUnderLabel' for='genre3'><span class='bfd'>O</span>" . "$entry1_odds_ou_6_cmp" . "</label><input type='checkbox' name='genre3' value='overUnderOdds1' DISABLED /><br />\n";
echo "<label id='overUnderLabel' for='genre4'><span class='bfd'>U</span>" . "$entry2_odds_ou_6_cmp" . "</label><input type='checkbox' name='genre4' value='overUnderOdds2' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay1_ou_6" . "</td>\n";
echo "</tr>\n";
echo "<tr>\n";
echo "<td>" . "$entry2_rot_6" . "</td>\n";
echo "<td id='teamNameData'>" . "$entry2_name_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$point_spread2_sp_6_cmp" . " " . "$entry2_odds_sp_6_cmp" . "</label><input type='checkbox' name='genre5' value='102odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_sp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre5'>" . "$entry2_odds_pwp_6_cmp" . "</label><input type='checkbox' name='genre5' value='105odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_pwp_6" . "</td>\n";
echo "<td id='odds'><label class='bfd' for='genre6'>" . "$entry2_odds_ml_6_cmp" . "</label><input type='checkbox' name='genre6' value='100odds' DISABLED /></td>\n";
echo "<td id='olPercent'>" . "$overlay2_ml_6" . "</td>\n";
echo "<td id='olPercent'>" . "$overlay2_ou_6" . "</td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "</div>\n";
echo "<hr />\n";
echo "<input type='hidden' name='total_games' id='total_games' value=" . "$total_games" . " />\n";
echo "<input type='submit' value='Continue' class='f-submit' />\n";
echo "&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type='button' value='Reset' id='resetform' class='f-submit' onClick='resetForm()' /><br />\n";
echo "</form>\n";
?>
